resend/react-email

packages/html/.eslintrc.js
packages/html/license.md
packages/html/package.json
packages/html/readme.md
packages/html/src/html.tsx
packages/html/src/index.ts
packages/html/tsconfig.json

Closes https://github.com/zenorocha/react-email/issues/9
> Note: Saw some references to use `xmlns="http://www.w3.org/1999/xhtml"` on the HTML tag, but got some Typescript complains about it. So, not really sure if it's really necessary.

feat(html): Add `Html` component

---

packages/avatar/src/avatar.tsx

Not sure if it was intentionally written in 🇮🇹 , or was a mistake.
I opened this small contribution by changing it to how we write in 🇺🇸 .

fix(Avatar): change abbreviete to abbreviate

---

packages/avatar/package.json
packages/eslint-config-custom/package.json
yarn.lock

noticed a lot of console warnings when running `yarn install`, we missed adding a few explicit dependencies to some packages

chore: Add missing dependencies

---

packages/react-email/source/utils/watcher.ts

Using the `dev` (`email dev`) command on Windows now throws the following error:
```
node:internal/process/promises:288
triggerUncaughtException(err, true /* fromPromise */);
^
NestedError: Cannot copy `M:\path\to\react-email-starter\emails/undefined`: the file doesn't exist
at M:\path\to\react-email-starter\node_modules\cpy\index.js:96:10
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async FSWatcher.<anonymous> (M:\path\to\react-email-starter\node_modules\react-email\dist\utils\watcher.js:34:9) {
nested: undefined,
name: 'CpyError'
}
```
This is because Windows sets the path separator as "\\" instead of "/".  
Thus, it appears that the `file[1]` being accessed on the last line is `undefined`, and the command is crashing.

fix(react-email): Split path separator on Windows

---

packages/react-email/package.json
packages/react-email/source/commands/dev.ts
yarn.lock

Ideally, running `email dev` should install packages with the user's preferred package manager.
With `detect-package-manager`, this change first attempts to detect the PM based on the lockfile. If none exists, it checks for global installation of `yarn`, then `pnpm`. If neither of those are installed, it defaults to `npm` which is already installed with Node. See https://github.com/egoist/detect-package-manager/blob/main/src/index.ts.
Closes https://github.com/zenorocha/react-email/issues/246

feat(react-email): Detect package manager in  command

---

packages/react-email/source/commands/dev.ts

When running `react-email dev` on fresh project, there was error occured sometimes. And error was occured when `createAppFiles` function creating `./react-email/src/pages/preview/[slug].tsx` file, because `writeFile` function doesn't wait `createDirectory` function to finish.

fix(react-email): cli crash

---

packages/react-email/preview/src/components/code-container.tsx
packages/react-email/preview/src/components/code.tsx
packages/react-email/preview/src/pages/preview/[slug].tsx
packages/react-email/preview/src/utils/language-map.ts

This PR changes the "view mode" of the generated code by replacing two vertical columns with a single container. The "Download" and "Copy to Clipboard" features continue to work according to the `activeTab`.
The `<CodeContainer markups={[...any markups]} />` component now manages how many markups are provided, generating a respective _tab_ and _content_ for each one.
https://user-images.githubusercontent.com/8185819/210676547-f463d03d-4f22-44bc-92fa-e94a546b2dfe.mp4

feat(preview): Add single code container in order to simplify preview

---

packages/react-email/source/commands/export.ts

This PR fixes https://github.com/resendlabs/react-email/issues/293 where it exits the process after success.

fix(react-email): Exit process

---

apps/docs/getting-started/automatic-setup.mdx
apps/docs/getting-started/manual-setup.mdx

Two images in the `Getting Started` section had urls set to invalid paths. This PR fixes that

fix(docs): Path to image

---

readme.md

closes #369
Adds the missing heading component in the root readme

fix(root): Add `Heading` component to readme

---

apps/docs/changelog.mdx
packages/section/package.json

This PR bumps `<Section>` version after the recent fix from https://github.com/resendlabs/react-email/pull/312.

chore(section): Bump to `v0.0.5`

---

packages/react-email/package.json
packages/react-email/source/utils/watcher.ts

In the current version (1.7.2), if you were to change a file in (for example) `emails/components` the watcher would not copy that file to the correct location. This pr fixes this behaviour, see pictures below:
Before changing `header.tsx`:
After changing `header.tsx` (old flow):
After changing `header.tsx` (new flow):

fix(react-email): Watcher for subfolders

---

packages/react-email/source/index.ts
packages/react-email/tsconfig.json

I removed the hard-coded version and passed package.json's version
Note: `"resolveJsonModule": true` works because `esModuleInterop` is true

fix(react-email): Package.json version

---

packages/react-email/package.json

related to https://github.com/resendlabs/react-email/issues/248#issuecomment-1407272929
`react-email@1.7.7` raises "command not found" error.
I created a branch to reproduce it. Please check out [this](https://github.com/m-shaka/react-email/tree/repro-command-not-found) and run
```
yarn --force
yarn workspace repro-command-not-found dev
```
cause:
`dist/index.js` is not published.
https://www.npmjs.com/package/react-email/v/1.7.7?activeTab=explore
This is understandable because `build` command generate `dist/source/index.js` instead of `dist/index.js`.
You can see it through executing `yarn turbo build --scope=react-email` and then `ls packages/react-email/dist` manually.
I don't know `dist/index.js` had been published until 1.7.6 but it must be cache

fix(react-email): command not found error

---

packages/react-email/source/commands/dev.ts
packages/react-email/source/index.ts

- Added option to command line for dev server.
- Consolidated shell execution to a function as it was called in two places..
fixes https://github.com/resendlabs/react-email/issues/372

feat(react-email): Add custom port configuration

---

packages/tailwind/package.json
yarn.lock

This PR addresses a bug encountered when using the Tailwind component in the `react-email` package. The issue arose from some pre-compilers trying to access the `esm` file instead of the `commonjs` module. The solution was to update the `tw-to-css` package to its latest version, where the bug has been resolved.
To test, clone the `react-email` package and link it locally with the following command:
```sh yarn
yarn workspace @react-email/tailwind link
```
Next, link the package in a project for testing with:
```sh yarn
yarn link @react-email/tailwind
```
> This will allow you to use the package as if it were installed in your `npm_modules`.
After testing, unlink the package by running:
```sh yarn
yarn workspace @react-email/tailwind unlink
```

chore(tailwind): Update tw-to-css depedency

---

packages/head/src/head.tsx

This PR adds a ; in the declaration of the content properties of the meta tag. This correction was necessary because when testing some emails on the [Email On Acid](https://www.emailonacid.com/) platform, I noticed along with my coworker (@thudf) that some email providers were not recognizing words that had an accent. Here's an example:
The purpose was to write "olá".

fix(head): Meta tag content declaration

---

packages/react-email/package.json
packages/react-email/source/commands/dev.ts

Currently, the dev server only allows us (implicitly) to create the following folders inside the `email`-folder: `components` & `static`. Sub folders are not allowed inside the `components`-folder which can lead to a messy folder structure.
This PR allows us to create the folder structure we want/need for the project, while still moving the files in the `static`-folder to the `public`-folder for NextJS. A nice side-effect is that all files are now moved to the NextJS server, like custom interfaces in `.ts`-files or json data (fixes #379). Project example:
Before             |  After
:-------------------------:|:-------------------------:
Note: The watcher is already equip to deal with custom folder structures, so no change was needed there.

fix(react-email): Allow custom folder structure inside emails folder

---

packages/react-email/source/commands/dev.ts

fix #411 
This is caused by a bug of `detect-package-manager`. See https://github.com/egoist/detect-package-manager/pull/7

fix(react-email): make NPM the default package manager

---

apps/demo/emails/yelp-recent-login.tsx

Hi all,
I noticed that in a few places `...paragraph` was included in the styling where it is unnecessary, because it only changes the `fontSize` propery.
```tsx
const paragraph = {
fontSize: 16,
};
```
So this is just making readability harder:
```tsx
<Heading
style={{
...paragraph,
fontSize: 32,
// ...
```

fix(demo): Remove unnecessary styles from Yelp

---

apps/docs/components/html.mdx
packages/html/src/html.tsx

Hello 👋, this pr adds `dir` prop which will benefit lots of `rtl` users e.g Arabic speaking users 
I checked the [compatibility](https://www.caniemail.com/features/css-direction/) to make sure it works on almost all email clients 
docs updated + ran lint to make sure everything is okay
before:
After:

feat(html): Add direction prop

---

packages/react-email/package.json
packages/react-email/source/commands/dev.ts
packages/react-email/source/commands/export.ts
packages/react-email/source/utils/watcher.ts
yarn.lock

Fix for cpy flatten copy. Found a solution using `shelljs` to copy files (including their folder structure) to the `.react-email` folder, without the use of the `spy`-package
Alternative for PR #454 
Closes #447

fix(react-email): Replace cpy with shelljs.cp

---

apps/docs/changelog.mdx
apps/docs/getting-started/manual-setup.mdx

This PR fixes two typos, one in `Changelog` and `Manual Setup`.

fix(docs): Typos

---

packages/react-email/source/utils/watcher.ts

There is an error when copying email templates from its folder to `.react-email` folder when `-d` argument is provided to `email dev` command with a nested path like `src/emails`. (`email dev -d src/emails`).
The error was the following:
```node
node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
^
NestedError: Cannot copy `/home/xxx/projectRoot/src/emails/emails/biweekly-event-reminder.tsx`: the file doesn't exist
at /home/dani/glissandoo/functions/node_modules/cpy/index.js:96:10
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async FSWatcher.<anonymous> (/home/dani/glissandoo/functions/node_modules/react-email/dist/source/utils/watcher.js:38:9) {
nested: undefined,
name: 'CpyError'
```
This happened because `cwd` in …

fix(react-email): Support nested email paths

---

packages/tailwind/.babelrc
packages/tailwind/jest.config.js
packages/tailwind/package.json
packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/tailwind.tsx
yarn.lock

This PR brings some upgrades to the Tailwind component:
Using responsive styles is not something that can be done inline, so when adding responsive styles, the component will automatically place its code in the `style` tag inside the `head` tag of your email, which is why `html` and `head` tags are required in your code. For example:
```tsx
<Tailwind>
<Html> // <-- Required
<Head /> // <-- Required
<Section>
<div className="bg-red-200 sm:bg-red-300 md:bg-red-400 lg:bg-red-500" />
</Section>
</Html>
</Tailwind>
```
Some changes were also necessary to make this happen, such as escaping the class names because some email clients do not support them.
> **Before:** `md:bg-red-400 `
> **After:** `md_bg_red_400`
In the past, we used `React.Children` to nest components. But it didn't play nice …

chore(tailwind): Add support for responsive classes and custom nested components

---

packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/tailwind.tsx

This PR should fix this issue (https://github.com/resendlabs/react-email/pull/502#issuecomment-1445639455) reported by @ysm-dev
> Looks there is some bug on this PR. Suddenly, My Button Component got weird style `padding: 0px 0px` after bump this package to `0.0.5` so my tailwind styles are ignored.
> 
> <img alt="image" width="599" src="https://user-images.githubusercontent.com/18487241/221466155-e3af116e-687e-45db-8d63-aa4be400d7ee.png">
> 
> <img alt="image" width="265" src="https://user-images.githubusercontent.com/18487241/221466176-2a3b783b-f572-4490-810e-38990668ce05.png">

fix(tailwind): Tailwind should override default inline styles

---

packages/tailwind/package.json
yarn.lock

This PR updates the `tw-to-css` module to v0.0.11, which fixes these bugs:
- https://github.com/resendlabs/react-email/issues/512
- https://github.com/resendlabs/react-email/issues/506
Issue on `tw-to-css`: https://github.com/vinicoder/tw-to-css/issues/2

chore(tailwind): Update tw-to-css to v0.0.11

---

packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/tailwind.tsx

Fix for #518
Tailwind classes with `/` (forward slash), `.` (period), and `%` (percent) were not getting transformed with the underscore correctly. 
I added regex for:
- replacing the dom attribute characters
- correctly matching on selectors
- replacing selector characters (i used a look ahead here in order to not grab the class's initial `.`)
So far its been a good journey using this lib! Let me know if this needs anything else. 
I also added tests for my use cases

fix(tailwind): Regex classes with `.`, `/`, and `%`

---

packages/container/src/container.tsx

closes https://github.com/resendlabs/react-email/issues/529

fix(container): Missing `tbody`

---

packages/react-email/source/commands/export.ts

Fix this
```
❮ yarn export                                                                                                    
⠋ Preparing files...
/react-email-starter/out/notion-magic-link.js:38320
loginCode = "sparo-ndigo-amurt-secan"
^
TypeError: Cannot read properties of undefined (reading 'loginCode')
at Object.NotionMagicLinkEmail (/react-email-starter/out/notion-magic-link.js:38320:3)
at exportTemplates (/react-email-starter/node_modules/react-email/dist/source/commands/export.js:61:64)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.15.0
```
The mail is https://github.com/resendlabs/react-email/blob/d9628ecdf69723f4810c51a4da7cd06efd16e3d8/packages/create-email/template/emails/notion-magic-link.tsx#L23

fix(react-email): Export default props

---

packages/create-email/template/package.json

Fix this issue
```
$ yarn --version
3.4.1
$ yarn create email
$ cd react-email-starter
$ yarn dev
✔ Emails preview generated
⠋ Installing dependencies...
Usage Error: The nearest package directory (/react-email-starter/.react-email) doesn't seem to be part of the project declared in /react-email-starter.
- If /react-email-starter isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /react-email-starter is intended to be a project, it might be that you forgot to list .react-email in its workspace configuration.
- Finally, if /react-email-starter is fine and you intend .react-email to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.
```

feat(create-email): Add `package.json` workspaces

---

packages/react-email/source/utils/start-server-command.ts

For some reason this bug came back, it was previously fixed here #417.
Also, I noticed a canary release was published under the `latest` tag on npm, should watch out for that.

fix(react-email): Dev server commands

---

docs/changelog.mdx
packages/react-email/package.json
packages/react-email/source/utils/generate-email-preview.ts

This PR changes how we handle `static` files. The `static` files should live outside of `emails` folder.

feat(react-email): Move `static` files outside of `emails` folder

---

packages/render/src/index.ts
packages/render/src/renderAsync.spec.tsx
packages/render/src/renderAsync.ts

closes https://github.com/resendlabs/react-email/issues/493
> My implementation checks if `renderToStaticMarkup` is defined. If not `renderToReadableStream` is used and the stream is converted to a string.
> 
> It would be nice to have something like this directly integrated in react-email, but it requires the introduction of an async function like `renderAsync` to work, so we are not introducing a breaking change for the `render` function. I could create a pull request with my changes and add it to the docs if you are ok with creating a `renderAsync` function.

feat(render): Add renderAsync function to enable edge runtime support

---

packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/tailwind.tsx

Current elements in the `<head/>` are not being being handled properly when responsive styles are present using the tailwind component.
For example, you cannot use the `<Font/>` component right now if you are using tailwind with responsive styles. 
This merge request just passes all existing elements in the `<head/>` through, and adds the `<style/>` tag for the new classes being added.
The end result is all elements you have in the `<head/>`, plus an additional `<style/>` tag with the tailwind styles.

fix(tailwind): Persist existing head elements when responsive styles are present

---

packages/react-email/source/utils/start-server-command.ts

Even after the last fix to this file #617 , I still haven't been able to have a clean exit from the dev server. In order for my shell to officially exit, i need to kill all node processes in OSX's activity monitor. 
I think I covered the rest of the stackoverflow answer, react-email was missing the shell exit.
Let me know how else I can help!

fix(react-email): Exit shell on SIGINT

---

.vscode/settings.json
docs/integrations/aws-ses.mdx
examples/aws-ses/package.json
examples/aws-ses/src/index.tsx
examples/aws-ses/yarn.lock
yarn.lock

Using the `aws-sdk` is a little bit outdated since AWS does not include them in the Node v18 Lambdas, and they are pushing the new AWS SDK v3 instead.
I've updated the AWS SES example to use the new SDK.
I could've duplicate the examples to have the v2 and v3 SDK, let me know if it's better or not.

refactor(examples): Use AWS SDK v3 for SES example

---

docs/getting-started/automatic-setup.mdx

The current doc says `pnpm` which would not install dependencies
pnpm install command should be `pnpm install` or `pnpm i`

chore(docs): Update install command

---

demo/emails/twitch-reset-password.tsx

This PR moves whitespaces out of link tags to avoid link decorations to extend into whitespace between words like
```diff
- please[ reset your account password](https://demo.react.email/preview/twitch-reset-password#)
+ please [reset your account password](https://demo.react.email/preview/twitch-reset-password#)

chore(react-email): add consistent twitch demo link whitespace

---

packages/components/package.json

This adds exports config to the package.json so Node in Native ESM mode can resolve imports to the right files.
Closes #513

fix(components): Add exports for Native ESM support

---

packages/react-email/source/utils/watcher.ts

Fix: #636
When launching `npm run dev` and ctrl+c, the process is hanging forever.
After a quick search, I realised chokidar is never closed. 
This might not be the best place to listen to ctrl+c, but it's also handy that the instance is autonomous since the ctrl+c can happen at any moment.

fix(react-email): Preventing the process to close

---

packages/button/src/button.spec.tsx
packages/button/src/button.tsx

Per Typescript definition, padding is optional to the button component, especially if people using Tailwind CSS, props won't be provided. in this case we will be outputting `undefined` inline CSS.
Adding default value for pX, pY in the PR, we could also consider ignoring rendering those value if the props is undefined.

fix(button): Provide default value for button padding

---

packages/font/src/font.spec.tsx
packages/font/src/font.tsx

Maybe I'm crazy or missing something significant, but the `Font` component generates markup that is full of HTML entities and doesn't seem to work with those entities. I suspect something similar is probably going on for https://github.com/resendlabs/react-email/issues/442.
What am I missing? ~~I can't find any indication that style blocks are supposed to use HTML entities, but it's a big internet out there.~~ HTML 4 spec is pretty explicit that [`style` elements should not contain character references](https://www.w3.org/TR/1998/REC-html40-19980424/types.html#:~:text=style%20sheet%20data%20that%20is%20element%20content%20may%20not%20contain%20character%20references).
I'm happy to pursue a solution that uses something other than `dangerouslySetInnerHTML`, but I'm not sure what that would …

fix(font): Styles should not include HTML entities

---

client/src/components/code-container.tsx
client/src/components/code.tsx

When starting the dev server and accessing the `Source` view of an email, several warnings appear in the console.
This PR involves 2 components and fixes the following warnings:
- **code-container** - `Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.`
- **code** - `A props object containing a “key” prop is being spread into JSX [...] React keys must be passed directly to JSX without using spread`

fix(client): Console warnings

---

docs/integrations/aws-ses.mdx
docs/integrations/mailersend.mdx
docs/integrations/nodemailer.mdx
docs/integrations/plunk.mdx
docs/integrations/postmark.mdx
docs/integrations/resend.mdx
docs/integrations/scaleway.mdx
docs/integrations/sendgrid.mdx
examples/aws-ses/package.json
examples/nodemailer/package.json
examples/nodemailer/src/index.tsx
examples/nodemailer/yarn.lock
packages/tailwind/package.json
web/src/components/menu.tsx
web/src/pages/examples/index.tsx

We have done some housekeeping on the repo for you and also synced the official Nodemailer example.
Thank you! :pray:

fix(root): Links, sync nodemailer official example and aws-ses package.json

---

packages/heading/src/heading.tsx
packages/markdown/src/markdown.tsx

Hey, added missing export of props two packages: @react-email/heading and @react-email/markdown. 
I created one PR without conventional commit scope for this one, but if thats a problem then hmu about it and I will change it

fix(heading, markdown): Export types

---

packages/create-email/src/index.js

This PR fixes a spelling mistake in the description of the `dir` argument in `create-email`.

fix(create-email): spelling mistake for `dir` arg description

---

packages/react-email/source/commands/dev.ts
packages/react-email/source/index.ts
packages/react-email/source/utils/run-server.ts

This change is to stop us from getting a `yarn.lock` file added to our project starting the email dev server.
Since we use a monorepo we don't need the react-email server to manage installing deps and this is a way to opt-out with `--skip-install`.
Repo for context:
https://github.com/bautistaaa/typehero/tree/main/apps/email

feat(react-email): Add skip install flag

---

client/tsconfig.json
packages/react-email/source/utils/generate-email-preview.ts

This PR should fix #883.
The error message said that the extension (.tsx) is the problem. I just allowed the extension to be imported from emails folder
Sorry for dirty work history

fix(client): allow .tsx extension file can be imported from auto-generated emails folder

---

packages/markdown/jest.config.js
packages/markdown/package.json
packages/markdown/src/markdown.spec.tsx

`DOMPurify` has been removed from `md-to-react-email`.
This PR fixes #914.
- Developer Responsibility:
The primary purpose of this library is to allow developers to create email templates with markdown. Any potential vulnerabilities in the generated HTML content primarily result from the developers' input. Therefore, the need for DOMPurify to sanitize the Markdown output is minimal. Developers can opt to use it separately to ensure their content is safe.
- Compatibility on the Edge:
DOMPurify operates within the DOM (Document Object Model), and its behavior can be influenced by the surrounding context. This can lead to edge compatibility issues, especially in scenarios where the library is used in various contexts, such as server-side rendering or non-browser environments.
- Package Size: …

chore(markdown): upgrade md-to-react-email

---

packages/tailwind/src/tailwind.tsx

This PR fixes #922 #888
Current filter implementation filters out all class-names when it's trying to filter out non-responsive classes
Add an extra check to filter out only class-names that tailwind has styles for - class-names that map to tailwind styles, otherwise keep the class-names

fix(tailwind): Keep custom class-names 

---

packages/font/src/font.tsx

As many people use browsers to display their emails, in my opinion it makes sense to allow the [typical](https://www.w3schools.com/css/css_font_fallbacks.asp) font fallbacks like "sans-serif" in the fallbackFontFamily array.

fix(font): Allow the typical fallback-fonts

---

.github/workflows/tests.yml
packages/body/package.json
packages/button/package.json
packages/column/package.json
packages/container/package.json
packages/font/package.json
packages/head/package.json
packages/heading/package.json
packages/hr/package.json
packages/html/package.json
packages/img/package.json
packages/link/package.json
packages/markdown/package.json
packages/preview/package.json
packages/row/package.json
packages/section/package.json
packages/text/package.json
pnpm-lock.yaml

- use workspace devDependencies for packages used for testing only
- makes sure we build the packages before running tests
- merge lint + test
- remove unnecessary steps for checking pinned dependencies

chore: Use workspace devDependencies for react-email packages

---

README.md

With the latest `pnpm dev`, the website is opened at `localhost:3000` instead of `3001`. Not sure if that's intended. This PR is to update the port number.

chore(root): Update `readme.md` URL to `localhost:3000`

---

packages/render/src/render-async.spec.tsx
packages/render/src/render-async.ts

fixes https://github.com/resendlabs/react-email/issues/868
fixes https://github.com/resendlabs/react-email/issues/989

fix(render): Render async next 14

---

client/next.config.js

This pull request removes the no longer necessary appDir option from the next.config.js  (experimental) file in the react-email repository. The App Router is now stable as of Next.js 13.4, eliminating the need for this option.
changes:
- Removed experimental appDir option from next.config.js.

fix(react-email): Remove obsolete appDir option from next.config.js

---

package.json
packages/components/package.json
packages/tailwind/package.json
packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/tailwind.tsx
packages/tailwind/src/utils/css-to-jsx-style.spec.ts
packages/tailwind/src/utils/css-to-jsx-style.ts
packages/tailwind/src/utils/get-css-for-markup.ts
packages/tailwind/src/utils/minify-css.ts
packages/tailwind/src/utils/use-rgb-non-spaced-syntax.spec.ts
packages/tailwind/src/utils/use-rgb-non-spaced-syntax.ts
packages/tailwind/tsconfig.json
packages/tailwind/tsup.config.ts
patches/tailwindcss@3.3.2.patch
pnpm-lock.yaml

This fixes problems a user from Discord had with server actions and bundles the packages
that we have fixed internally through patches so that the patches are sent to the users
and so that the Tailwind component works the same for users as it does running in dev locally.
This also replaces all `rgb(red green blue / alpha)` with `rgb(red,green,blue,alpha)` that works better for some more email clients like gmail.
Now fixes a parsing problem we had when generating the object for the styles and another problem that was happening with vite builds due to tailwind's CLI code being bundled in as well.

fix(tailwind): Extra rough edges

---

docs/integrations/resend.mdx

I think the docs for Resend integration is using an outdated version. According to the https://resend.com/docs/api-reference/emails/send-email it's now
```js
import { Resend } from 'resend';
const resend = new Resend('re_123456789');
await resend.emails.send({
from: 'Acme <onboarding@resend.dev>',
to: ['delivered@resend.dev'],
subject: 'hello world',
text: 'it works!',
attachments: [
{
filename: 'invoice.pdf',
content: invoiceBuffer,
},
],
headers: {
'X-Entity-Ref-ID': '123456789',
},
tags: [
{
name: 'category',
value: 'confirm_email',
},
],
});
```

docs(resend): update resend code example

---

packages/render/src/render-async.ts
packages/render/src/render.spec.tsx
packages/render/src/render.ts

We're having customer support inquiries that links in our plain text emails lead to nonexistent or broken pages. Customer support have identified that the issue is that users are either copying links but not removing the bracket, or their email clients are not stripping the trailing bracket `]`.
I've investigated how `react-email` generates the plain text emails, and it comes down to a package called `html-to-text`.
https://www.npmjs.com/package/html-to-text
This library has the option to either disable or configure the brackets via the option `linkBrackets`.
I've simply disabled brackets since `html-to-text` isn't optimized for compatibility with email clients and this seems like the simplest solution.
> Side note: it's impossible for us to patch the `@react-email/render` package with …

feat(render): Remove brackets surrounding anchor tags with plain text option

---

packages/react-email/source/utils/generate-email-preview.ts

This PR resolves an issue when generating emails previews, currently if you have any spec or test file within this directory these are picked up as they end in the `jsx` or `tsx` extension.

feat (react-email): Ignore test files when generating email previews

---

docs/changelog.mdx

**Render `0.0.11`**
- Replace unmaintained `pretty` package for `js-beautify` (thanks [Bastien Robert](https://github.com/bastienrobert))
- Remove link brackets surrounding links on plain text rendering (thanks [Marcus Stenbeck](https://github.com/marcusstenbeck))
- Fix functions called from `react-dom/server` to avoid them being called and
causing issues on NextJS on the edge
- Add an option for the `render` and `renderAsync` functions to customize the
[htmlToText](https://www.npmjs.com/package/html-to-text) options
**Tailwind `0.0.14`**
- Fix an error for a hack that is used on Tailwind to detect a deprecated
dependency taht fails when it is being bundled on NextJS
- Fix issues that were being caused by calling `renderToStaticMarkup` by doing
a very archaic rendering of the JSX to just …

feat(docs): Add changelog for Jan 16, 2023

---

apps/web/src/pages/examples/index.tsx

Or maybe we should move `demo` back to `apps/demo`

fix(web): Demo folder location on GitHub

---

demo/emails/vercel-invite-user.tsx

I noticed this minor typo when checking out the examples on [https://demo.react.email/preview/vercel-invite-user?view=source&lang=markdown](https://demo.react.email/preview/vercel-invite-user?view=source&lang=markdown).
The issue is best visible in the text rendered version.

fix(examples): resolve whitespace typo

---

packages/code-block/src/code-block.tsx

Sometimes with the current version, some tokens would not be rendered
because we were missing treating an edge case where the token
is a stream of other tokens. They would be missing and look something like:
1. Run `pnpm build` inside of `./packages/code-block`
2. Add `@react-email/code-block` as a dep of `./apps/demo` as follows:
```json
{
"dependencies": {
"@react-email/code-block": "../../packages/code-block"    
}
}
```
3. Add an `email.tsx` inside of `./apps/demo/emails` with the following content:
```tsx
import { CodeBlock, nightOwl } from '@react-email/code-block';
export default function Email() {
const code = `export default async (req, res) => {
try {
const html = await renderAsync(
EmailTemplate({ firstName: 'John' })
);
return NextResponse.json({ html });
} catch (error) { …
```

fix(code-block): Certain tokens not being rendered

---

packages/create-email/template/package.json

When running `npx create-email@latest` and then running `npm run dev`
on it there would be issues when rendering any email preview because
of React missing as a dependency.
This is something that has changed from the old preview server as
we now do bundling of the email templates instead of loading them in through
imports which makes it so that the emails `package.json` can go by without `react` 
as a dependency.
1. Go into `./packages/create-email`
2. Run `node ./src/index.js`
3. Go into `react-email-starter`
4. Run `npm install` or anything else except for `pnpm install`
5. Run `npm run dev`
6. Open http://localhost:3000
7. Open any email and verify it does not error with `ERROR: Could not resolve "react/jsx-runtime"`

fix(create-email): Issues when running `dev` command on `react-email-starter`

---

packages/code-block/src/code-block.tsx

Styles are not being added to tokens that should be added. This resulted
in the syntax highlighting not matching Prismjs's default. This was fixed by 
moving the styles related to the token type or its aliases down into the token tree.
<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

fix(code-block): Highlighting not matching usual Prismjs's highlighting

---

packages/react-email/src/actions/get-emails-directory-metadata.ts

Someone from Discord came to me reporting that they weren't being able to see their emails
on the Sidebar of the preview app. This was caused due to an unnecessary regex that was testing
whether or not the path to the email had a `_` at the start of any of its segments meaning
that it would fail if the user had a project either being the one or being inside a directory prefixed with `_`.
Here's the code with the issue:
https://github.com/resend/react-email/blob/7028a581bac498bec90dce91277e0ec1de8f3221/packages/react-email/src/actions/get-emails-directory-metadata.ts#L6-L13
1. Rename the folder at `./apps/demo` into `./_apps/demo`
2. Run `npx tsx ../../packages/react-email/src/cli/index.ts dev` inside of `./_apps/demo`
3. Open http://localhost:3000
4. Verify that all the emails are …

fix(react-email): Emails parent folder with `_` prefix

---

packages/react-email/src/contexts/emails.tsx
packages/react-email/src/utils/emails-directory-absolute-path.ts

Hot reloading was not working if the custom directory was two folders deep.
This was because of a missing treatment I didn't add to where the changes are detected:
https://github.com/resend/react-email/blob/7028a581bac498bec90dce91277e0ec1de8f3221/packages/react-email/src/contexts/emails.tsx#L72-L83
This split, slice, and join technique would not work for deeper custom directories
then at the CWD where the user is running the `dev` command.
1. Open the terminal on `./apps/demo`
2. Temporarily move the `./apps/demo/emails` folder into `./app/demo/src/emails`
3. Run `npx tsx ../../packages/react-email/src/cli/index.ts dev -d ./src/emails` inside of `./apps/demo`
4. Open http://localhost:3000
5. Click on any email and make some changes to it
6. Verify that the email updates appropriately …

fix(react-email): Hot reloading not working with custom emails directory

---

packages/code-block/src/prism.ts
packages/react-email/src/cli/commands/export.ts
packages/react-email/src/cli/utils/preview/start-dev-server.ts

It fixes two things. First it fixes that the sub directories were not taken into account
by the `email export` command which gave a discrepancy between it and `email dev`'s behavior.
Secondly, it fixes the duplication of `./out/static` directories like the following:
```javascript
out
└── static
├── notion-logo.png
├── plaid-logo.png
├── plaid.png
├── static
|   ├── notion-logo.png
|   ├── plaid-logo.png
|   ├── plaid.png
|   ├── stripe-logo.png
|   ├── vercel-arrow.png
|   ├── vercel-logo.png
|   ├── vercel-team.png
|   └── vercel-user.png
├── stripe-logo.png
├── vercel-arrow.png
├── vercel-logo.png
├── vercel-team.png
└── vercel-user.png
```
1. Apply the same change as #1214 because without it `email export` will error
2. Create the directory `./apps/demo/emails/magic-links`
3. Move …

fix(react-email): `email export` with sub directories and duplication of static files inside of `out/`

---

packages/react-email/src/cli/commands/export.ts

Errors like the following when running `email export`:
```bash
TypeError: component.default is not a function
at /Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:778:75
at step (/Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:186:23)
at Object.next (/Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:127:20)
at asyncGeneratorStep (/Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:12:28)
at _next (/Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:30:17)
```
This was happening because of a `await import` …

fix(react-email): ESM Issue with `await import` of the compiled email templates

---

packages/react-email/src/cli/utils/preview/start-dev-server.ts
packages/react-email/src/utils/emails-directory-absolute-path.ts

Shoutout to @filipewine for reporting this to me
@filipewine reported to me an error he was having on Windows similar to the following:
```javascript
> email dev -p 3030
React Email 2.0.0
Running preview at:          http://localhost:3030
⠙ Getting react-email preview server ready...
Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
at findPagesDir (G:\projects\next13-ticketing-app\node_modules\react-email\node_modules\next\dist\lib\find-pages-dir.js:42:15)
at initialize (G:\projects\next13-ticketing-app\node_modules\react-email\node_modules\next\dist\server\lib\router-server.js:71:69)
at async NextCustomServer.prepare (G:\projects\next13-ticketing-app\node_modules\react-email\node_modules\next\dist\server\next.js:240:28)
shutting down dev …
```

fix(react-email): Windows issue making the CLI's location not be found

---

packages/code-block/src/prism.ts
packages/react-email/src/app/preview/[slug]/page.tsx
packages/react-email/src/cli/utils/preview/start-dev-server.ts
packages/react-email/src/components/sidebar/sidebar.tsx

This solves this things in the same way:
1. All of the preview pages de-opting into client-side rendering with warnings (see https://nextjs.org/docs/messages/deopted-into-client-rendering)
2. Build failing because of `useSearchParams` inside of `packages/react-email/src/components/sidebar/sidebar-directory-children.tsx`. (see https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout)
Both of these were fixed by adding a Suspense boundary first here:
https://github.com/resend/react-email/blob/6a5cdf392b3742174caa3f26749d9e4fadcab31d/packages/react-email/src/app/preview/%5Bslug%5D/page.tsx#L39-L47
Then here:
https://github.com/resend/react-email/blob/6a5cdf392b3742174caa3f26749d9e4fadcab31d/packages/react-email/src/components/sidebar/sidebar.tsx#L32-L41
1. Run `npx tsx …

fix(react-email): Missing suspense boundaries

---

packages/code-block/src/prism.ts
packages/react-email/src/cli/commands/export.ts
packages/react-email/src/cli/utils/preview/start-dev-server.ts

This fixes an issue that would happen once the `package.json`'s `type` was set to "module"
and the user ran `email export`. The error looked something like the following:
```javascript
failed when rendering email.jsx
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'projectpath/package.json' 
contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```
This fixes that by setting the outExtension for esbuild to be `.cjs` and adjusting
the following pieces of code that dependend on it being `.js`.
1. Add `"type": "module"` inside of `./apps/demo/package.json`
2. Run `tsx ../../packages/react-email/src/cli/index.ts export` inside of …

fix(react-email): `email export` failing due to non-cjs file extension

---

packages/react-email/src/app/preview/[slug]/preview.tsx
packages/react-email/src/components/shell.tsx

Because of a fix I made for the mobile preview app's Sidebar being transparent
it caused the tooltip for toggling the Sidebar to be bellow it due to its z-index.
The way I fixed this was by just adding the larger z-index when the user was on mobile.
1. Run `npx tsx ../../packages/react-email/src/cli/index.ts dev` inside of `./apps/demo`
2. Open http://localhost:3000
3. Hover the button to toggle the sidebar
4. Verify that the tooltip is above the sidebar

fix(react-email): Sidebar toggle tooltip & email preview's iframe default background

---

packages/react-email/src/cli/commands/export.ts

I made a previous PR #1279 that fixed the subdirectory support for `email export`
but forgot to change a small detail which was causing the emails on sub-directories to not be rendered making 
an `out/` structure that would render the ones at the root but leave the `.cjs` artifacts for the ones at sub
directories.
```bash
out
├── email.html
├── folder
│   └── email.cjs
├── notion-magic-link.html
├── static
└── testing-tw-merge.html
```
This was fixed by just modifying the glob that would look for the `.cjs` artifacts of email templates
built with `esbuild`.
---
The other thing was that the support for `.js` email files on `email export` is just not there. 
Meaning that if you had `.js` files with `jsx` syntax in them `esbuild` would throw errors
saying `jsx` support is not enabled. This …

fix(react-email): Export not rendering files from sub directories

---

packages/create-email/package.json
packages/create-email/template/package.json
packages/react-email/package.json

`react-email` -> `2.1.0-canary.1`
`create-email` -> `0.0.23-canary.1`

chore(react-email, create-email): Bump for .1 canary release

---

packages/react-email/src/cli/commands/dev.ts

Static files not loading when using a custom directory due to their location
being hardcoded to `./emails`.
1. Move `./apps/demo/emails` into `./apps/demo/src/emails`
2. Run `npx tsx ../../packages/react-email/src/cli/index.ts dev -d ./src/emails` inside of `./apps/demo`
3. Open http://localhost:3000/preview/airbnb-review.tsx
4. Verify that the images are loading properly

fix(react-email): Hard coded value for location of static files

---

packages/button/src/button.spec.tsx
packages/button/src/button.tsx
packages/tailwind/src/tailwind.spec.tsx

The issue is that if the user were to define a `line-height`, or a few other styles,
through the `style` prop to the Button they would be ignored and ours would be preferred.
This PR changes that in the sense that if the user does provide this, then their value is
used instead of ours. This is not done for the padding prop though as it is already being
just computed from the one the user provides.
There is not much of a need for testing manually here since I have added in a unit test
to make sure that the style properties provided by the user do override ours.

fix(button): User styles not being overwritten by ours

---

packages/react-email/src/cli/commands/build.ts

A warning would always be added to the terminal saying `sharp` was missing once the user ran `email build`
because of Next not being able to do image optimizations. I fixed this by modifying the file at `./.react-email/package.json` relative to the user's project
and adding `sharp` as a dependency there. This wasn't much of a hassle as we already modified
it to add the start and build scripts.
1. Run `npx tsx ../../packages/react-email/src/cli/index.ts build` inside of `./apps/demo`
2. Verify that there are no `sharp missing` warnings

feat(react-email): Add sharp as a dependency on build

---

packages/react-email/src/cli/commands/build.ts

This would fix the errors that would look like the following:
This was being caused by a hard coded environment variable
being passed onto the preview app which came from the earlier
attempt at rendering the emails in a different way instead
of doing SSG. This was fixed by just copying the variable into it.
This also fixes the static folder not being properly copied which 
I noticed was the case here as well because of a hard coded value
too.
1. Move `./app/demo/emails` into `./app/demo/src/emails`
2. Run `npx tsx ../../packages/react-email/src/cli/index.ts build -d ./src/emails`
3. Verify that it doesn't error as the image shown before
4. Verify that the static files from `./app/demo/src/emails/static` were 
copied into `./app/demo/.react-email/public/static`

fix(react-email): Build not working with custom emails directory

---

apps/docs/getting-started/manual-setup.mdx

Simple fix after going through the docs 🫡 - `monoorepos` -> `monorepos`

chore(docs): Fix "monorepos" typo in Manual Setup guide

---

packages/button/package.json
packages/components/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/react-email/package.json
pnpm-lock.yaml

button -> 0.0.14-canary.0
components -> 0.0.15-canary.2
react-email -> 2.1.0-canary.2
create-email -> 0.0.23-canary.1

chore(react-email, create-email, components, button): Bump for canary release

---

apps/docs/getting-started/migrating-to-react-email.mdx

This pull request addresses a discrepancy in the documentation for migrating to React Email. Previously, the documentation referenced an `<Image>` component, which does not exist in react-email. I have adjusted the component to match the available image component `<Img>`.
**Changes:**
- Updated instance of <Image> to <Img> in the migration guide/docs.
This change does not affect any actual code, only the documentation, so no tests are needed. Please review and provide any feedback.
📨

fix(docs): correct <Image> tag to <Img> to align with import

---

packages/react-email/src/utils/get-email-component.ts

As we need to pre-import the modules from Node into the app before loading them with `vm`
we also need to define the context in which the code will run for us to get the email's component,
this means that we need to pass in a few other global things like `Buffer` that the `global`
dynamically doesn't contain.
That being said, something that was missing from the global context was the `URL` class,
which this PR adds. Closes #1229 
1. Run `npx tsx ../../packages/react-email/src/cli/index.ts dev` inside of `./apps/demo`
2. Modify the email at `./apps/demo/emails/airbnb-review.tsx` by adding the following:
```javascript
console.log(new URL(""));
```
3. Open http://localhost:3000/preview/airbnb-review.tsx
4. Verify that this errors with "Invalid path" instead of with `URL is not defined`

fix(react-email): Missing URL on global context for email VM

---

packages/tailwind/readme.md
packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/tailwind.tsx
packages/tailwind/src/utils/escape-class-name.ts
packages/tailwind/src/utils/sanitize-class-name.spec.ts
packages/tailwind/src/utils/sanitize-class-name.ts

This PR changes how the media query class names are kept by removing
escaping characters from them and replacing the ones they were meant
to escape with other characters that have better CSS support. Closes #1095.
Besides this, I also added in something I think is really important.
I added [Contributing notes](https://github.com/resend/react-email/pull/1114/files#diff-d5f010753aedd069206ab7ace5ccab1e79d89c40f3dbe2228539e7b450cc1c17) that mention the decisions
taken to modify the CSS generated by Tailwind and how it is applied to the email
for better email client support and for us to not lose these.
Would also be a great idea to write unit tests for these email support decisions, so we 
don't lose them by checking on a CI basis as well.
You can take a look into how I implemented the unit …

fix(tailwind): Media query escaped class names

---

packages/tailwind/src/__snapshots__/tailwind.spec.tsx.snap
packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/tailwind.tsx

After the Tailwind performance improvements, we changed things so that the
requirement for the `<head>` element being there — when using Tailwind classes that
had media queries — went from being
> You need to have a `<html>` followed by a `<head>` element or `<Head>` component
to being
> You need a `<head>` directly bellow your `<tailwind>` component
This change was for two reasons mostly:
1. To avoid having to execute regexes on the rendered markup to determine if the 
elements were included
2. To making the error message more clear while still being concise
This ended up causing two issues: 
1. You just could not use Tailwind classes on your `<Html>` tag anymore
2. Upon being minifying the function's name for our `<Head>` component would be changed
to something other than "Head" which …

fix(tailwind): Head component minification issue

---

packages/react-email/src/cli/commands/build.ts
packages/react-email/src/cli/utils/preview/start-dev-server.ts

When running the Next app we do a few path transformations by hand, as they run in the browser, and
browsers doesn't provide us with something like a `path` module. This means that we do stuff like making a path
relative to another by doing replacements. 
Here's an example of making a path relative and of where the issue starts: 
https://github.com/resend/react-email/blob/2e16a60805606b9c297114398f37881150249d14/packages/react-email/src/components/sidebar/sidebar-directory.tsx#L31-L35
This path replacement would fail because this absolute path is determined based on the user's project location:
https://github.com/resend/react-email/blob/2e16a60805606b9c297114398f37881150249d14/packages/react-email/src/utils/emails-directory-absolute-path.ts#L30-L34
And since this path is being passed in …

fix(react-email): Absolute paths when trying to click emails on sub directories in the Sidebar

---

packages/components/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/react-email/package.json
packages/tailwind/package.json
pnpm-lock.yaml

`@react-email/tailwind` -> `0.0.15-canary.0`
`react-email` -> `2.1.1-canary.1`
`@react-email/components` -> `0.0.16-canary.1`
`create-email` -> `0.0.24-canary.1`

chore(react-email, create-email, components, tailwind): Bump for canary release

---

packages/components/package.json
packages/markdown/package.json
packages/markdown/src/__snapshots__/markdown.spec.tsx.snap
packages/markdown/src/markdown.spec.tsx
pnpm-lock.yaml

This PR fixes #1285 and upgrades `@react-email/markdown` package in `components`
cc: @gabrielmfern

fix(markdown, components): bump md-to-react-email to v5.0.2

---

packages/react-email/src/cli/commands/export.ts

add in code to delete the PathToWhereEmailMarkupShouldBeDumped , out by default, if it already exists to make sure the directory only displays current and correct files when exporting to remove the chance of duplications and errors.

feat(react-email): Remove existing `out` directory when running `email export`

---

packages/react-email/.gitignore
packages/react-email/package.json
packages/react-email/src/cli/commands/dev.ts
packages/react-email/src/cli/utils/preview/hot-reloading/create-dependency-graph.spec.ts
packages/react-email/src/cli/utils/preview/hot-reloading/create-dependency-graph.ts
packages/react-email/src/cli/utils/preview/hot-reloading/get-imported-modules.spec.ts
packages/react-email/src/cli/utils/preview/hot-reloading/get-imported-modules.ts
packages/react-email/src/cli/utils/preview/hot-reloading/setup-hot-reloading.ts
packages/react-email/src/cli/utils/preview/index.ts
packages/react-email/src/cli/utils/tree.spec.ts
pnpm-lock.yaml

Our hot reloading currenlty works in the following way:
1. The user makes a change inside of the `emails` directory
2. `chokidar` detects it
3. We do a bit of debouncing to batch these changes together
4. We send them, through `socket.io`, into our preview Next app
Then in the Next app, we have a hook — specifically `useHotreload` — which receives
all the changes and then checks for email templates it knows exists to re-build
and re-render them.
This is mostly intended for #1366. It makes it so that, once a dependency of an email template changes,
the email template hot reloads. This improves the experience a bit more for users that have
separate components that they re-use across email templates.
Take the following email file structure:
```bash
emails/
├── _components
│   └── …
```

feat(react-email): Hot reloading with changes detection on dependencies of an email template

---

apps/docs/roadmap.mdx
packages/head/src/head.spec.tsx
packages/head/src/head.tsx
packages/tailwind/src/tailwind.spec.tsx

Meant to deal with #671. Since iOS is one of the most common renderers I figured it would make sense to add this as a default, especially since it is specific to that client it won't adversely affect any other clients.

feat(head): iOS formatting meta tag as default

---

packages/components/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/markdown/package.json
packages/react-email/package.json
packages/tailwind/package.json
pnpm-lock.yaml

- **chore(tailwind): Bump to 0.0.15**
- **chore(components): Bump dependency on @react-email/markdown to 0.0.9**
- **chore(components): Bump dependency on @react-email/tailwind to 0.0.15**
- **chore(components): Bump to 0.0.16**
- **chore(react-email): Bump dependency on @react-email/components to 0.0.16**
- **chore(react-email): Bump to 2.1.1**
- **chore(create-email): Bump template's dependency on @react-email/components to 0.0.16**
- **chore(create-email): Bump template's dependency on react-email to 2.1.1**
- **chore(create-email): Bump to 0.0.24**
- **chore(markdown): Bump to 0.0.9**
- **chore: Update lock**

chore(components, create-email, mardown, react-email): Bump for stable release

---

packages/create-email/template/emails/vercel-invite-user.tsx

The example imports Tailwind from `@react-email/tailwind` which is not install yet in package.json, so if user run the example and click `vercel-invite-user` demo, error occurs.

fix(create-email): Tailwind imported from @react-email/tailwind which is not installed

---

apps/docs/changelog.mdx

Adds in the same list of changes to the changelog as we have on our Releases.

chore(docs/changelog): Add entry for March 28, 2024

---

packages/tailwind/package.json
packages/tailwind/src/__snapshots__/tailwind.spec.tsx.snap
packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/tailwind.tsx
pnpm-lock.yaml

I noticed that, when testing to make sure that the new canary release of Tailwind actually had
#1391 fixed after #1335 being updated with the small Tailwind refactor from before, the `<Heading>` didn't
work like when I checked before the fixing of the conflitcs.
After debugging for a while, I noticed that, since we use `radix-ui`'s `<Slot>` component on the `<Heading>`,
it expects its children to be exactly one element, not an array, meaning that our mapping of children for elements
was making the `<SlotClone>` return `null` which made the `<Heading>` not render.
The fix for the issue was very simple — just looking at the array and checking if it
has only one value inside, in which case it would return that value instead of the
whole array. Otherwise, is just returning the plain array …

fix(tailwind): Children always being transformed into an array

---

packages/components/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/react-email/package.json
packages/tailwind/package.json
pnpm-lock.yaml

- **chore(tailwind): Bump to 0.0.16-canary.1**
- **chore(components): Bump dependency on @react-email/tailwind to 0.0.16-canary.1**
- **chore(components): Bump to 0.0.17-canary.1**
- **chore(react-email): Bump dependency on @react-email/components to 0.0.17-canary.1**
- **chore(react-email): Bump to 2.1.2-canary.0**
- **chore(create-email): Bump template dependency on @react-email/components to 0.0.17-canary.1**
- **chore(create-email): Bump template dependency on react-email to 2.1.2-canary.0**
- **chore(create-email): Bump to 0.0.25-canary.1**
- **chore: Update lockfile**

chore(components, create-email, react-email, tailwind): Bump for canary release

---

packages/react-email/package.json
pnpm-lock.yaml

A few times since we launched the `2.0.0` version of React Email's CLI,
there were a few people reporting issues that had errors like the following
when running `email dev`:
```
../@floating-ui/react-dom/dist/floating-ui.react-dom.mjs
Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'useLayoutEffect').
```
But I was never quite sure what was the culprit of this since the error
was pretty cryptic. 
Turns out this was [a NextJS bug](https://github.com/vercel/next.js/issues/60909) 
as I found out after someone from Discord made [a reproduction of the error](https://discord.com/channels/1022242959736983613/1225155457102905455/1225443577539203196).
This was fixed under https://github.com/vercel/next.js/pull/61791 and released under …

fix(react-email): Issue with `email dev` when there is a `browserslist` in the user's package.json

---

apps/docs/components/tailwind.mdx

This adds two things to the Tailwind component's docs. Mainly it adds a "Known limitations" section to make users aware
of limitations we currently have and are working towards improving. The limitations I wrote on were:
- Not yet Tailwind v3.4
- No support for `prose` from `@tailwindcss/typography`
- Limitations when trying to manipulate classes
The other, smaller, thing is an example of how Tailwind generated styles might not be compatible with all email clients.

feat(docs): Section for the Tailwind component's known limitations and improved style support callout

---

packages/react-email/src/utils/get-email-component.ts
packages/react-email/src/utils/improve-error-with-sourcemap.ts

Before the source map resolving was very archaic, this PR does a few adjustments to this improving
on how it resolves them, now based on all the sources of the source map, and on how it shows
the locations inside of the trace.
This also removes the useless part of the trace that was pointing inside of the `vm` node module
when the error happenned by trying to get the email's component.
|     Before     |     After      |
|----------------|----------------|
| ![image](https://github.com/resend/react-email/assets/88866334/59387576-ff31-4ede-b9e2-8ef918cbf04a)| ![image](https://github.com/resend/react-email/assets/88866334/c82ff160-699d-4f06-bf56-bda8ee1cab04) |
1. Change any email inside of `./apps/demo` to have errors
2. Run `tsx ../../packages/react-email/src/cli/index.ts dev` inside of …

feat(react-email): Improved error stack traces for preview server

---

package.json
packages/react-email/package.json
packages/render/package.json
pnpm-lock.yaml

This fixes all the dependency security vulnerabilities pointed out by Dependabot like:
- Vite dev server option `server.fs.deny` can be bypassed when hosted on case-insensitive filesystem
- due to an older version of `vitest` on `@react-email/render`
- Prototype Pollution in `merge`
- due to an older version of the, now unused, watch package 
This PR solves these issues by first upgrading `vitest` inside of `@react-email/render`
and by removing the dev dependency of `watch` from `react-email`, which doesn't relate to watching
of the email changes.

fix(react-email, render): Dependabot security vulnerabilities from dependencies

---

packages/react-email/src/utils/get-email-component.ts

Background
As we need to pre-import the modules from Node into the app before loading them with vm
we also need to define the context in which the code will run for us to get the email's component,
this means that we need to pass in a few other global things like Buffer that the global
dynamically doesn't contain.
What was the issue?
That being said, something that was missing from the global context was the URLSearchParams class,
which this PR adds. Similar to #1232.
How can I test to make sure it's fixed?
Run npx tsx ../../packages/react-email/src/cli/index.ts dev inside of ./apps/demo
Modify the email at ./apps/demo/emails/airbnb-review.tsx by adding the following:
console.log(new URLSearchParams(""));
Open http://localhost:3000/preview/airbnb-review.tsx
Verify that this errors with …

fix(react-email): Missing URLSearchParams on global context for email VM

---

apps/demo/package.json
apps/web/package.json
examples/resend/package.json
examples/scaleway/next/package.json
packages/render/package.json
packages/tailwind/package.json
pnpm-lock.yaml

This was missing from my last PR bumping the React dependency versions to `^18.2.0`. We need this to avoid peer dependency issues for users.

chore: Move all dependency versions of `react-dom` to `^18.2.0`

---

apps/demo/emails/notifications/vercel-invite-user.tsx
apps/demo/emails/welcome/netlify-welcome.tsx
apps/demo/package-lock.json
apps/demo/package.json

This is meant to fix the issue we were having that was causing
errors on our demo deploy. It was exactly the same issue as pointed out on #1432.
This can be seen to be working because the preview deploy of the demo on this PR is 
not failing.
The issue was that we were requiring `^18.2.0` on the `react-email` package, but for
all other packages we were requiring `18.2.0` exactly which meant it would conflict
on the peer dependencies. The solution was making all packages depend on `react@^18.2.0`.
From NPM's SemVer calculator, this new version resolves to the following currently:
- `18.2.0`
- `18.3.0`
- `18.3.1`
Meaning that if the user chooses to use any of these versions it won't complain about
the peer dependency version.
This PR simply updates the versions of `react-email` and …

fix: Error on demo deploy

---

packages/code-block/.prettierignore
packages/code-block/src/prism.ts
packages/react-email/src/utils/get-email-component.ts

Hello, I noticed `Headers` doesn't in the `get-email-component.ts`. Because of this, you can't see the preview of your email template if you are using `Headers` in your code. This PR should fix it. 
(BTW I spent 4 hours while investigating why tf is this can't find Headers 🤣)

fix(react-email): Missing Headers on the global context for email templates

---

packages/react-email/src/actions/get-emails-directory-metadata.ts
packages/react-email/src/cli/utils/preview/serve-static-file.ts

This fixes two security vulnerabilities pointed out by automatic
code analysis that could have caused access to files that don't
exist causing errors that could be quite hard to debug and find the cause of.
The first issue was inside of the function we use to server the user's static files,
i.e. `emails/static`, where if it found a certain path access was for a directory
like `http://localhost:3000/static/vercel` it would go directly into the index file without checking
it existed, which quite didn't make sense anymore so I removed that behavior and just respond
with a `404` in case the URL points into a directory.
The second issue was inside of the code we check if a file is an email,
inside of the server action called `getEmailsDirectoryMetadata`. It was reading
the file based on its …

fix(react-email): Possible file system race conditions

---

packages/react-email/package.json
packages/react-email/src/actions/render-email-by-path.tsx
packages/react-email/src/utils/__snapshots__/get-email-component.spec.ts.snap
packages/react-email/src/utils/get-email-component.spec.ts
packages/react-email/src/utils/get-email-component.ts
packages/react-email/src/utils/testing/email-template.tsx
pnpm-lock.yaml

This fixes the issues that were causing #649. What was causing that issue
was that `@react-email/render` would import `react-dom` as the Next 
bundled version, which would not be the same React instance used
inside the email templates, this caused that globals such as their
dispatcher would not have the expected values. 
I noticed this was the cause of that issue after looking at our
updated trace on the error, and it pointed down into the
bundled version of `react-dom` inside `next`. The same issue was
also happening for versions prior to `2.0`, so this was not a regression either.
To fix this, I added a simple esbuild plugin to when the email template
is loaded, so that it adds a `export { renderAsync } from '@react-email/render'`
at the end of it. This way, it would also give us access …

fix(react-email): Different react-dom version being used to render email templates

---

packages/create-email/template/package.json
packages/tailwind/src/tailwind.tsx
pnpm-lock.yaml

A while ago, I noticed that the types for our `TailwindConfig` type were wrong
as it was not completing any of the Tailwind properties. 
The issue was how we were defining it out of the default Tailwind `Config` type.

fix(tailwind): Types for TailwindConfig being basically a Record<string, any>

---

packages/tailwind/vite.config.ts

Current builds of `@react-email/tailwind` have the JSX runtime inlined (see occurences of `ReactCurrentOwner` in https://unpkg.com/@react-email/tailwind@0.0.16-canary.1/dist/index.js). It should be treated as an external package just like `react` and `react-dom`. Otherwise it may break between any release since React packages need to be used in lockstep. However, inlining the JSX runtime could mean that a consumer has 18.3 installed, while the library was published with an inlined version of 18.2

fix(@react-email/tailwind): Stop inlining JSX runtime

---

packages/tailwind/package.json

`@react-email/tailwind` declared `react` both as a direct and peer dependency. This means the peer dependency is rendered useless since the package manager will install a version of `react` right next to `@react-email/tailwind` instead of where it makes most sense to result in a single version `react` being used.
This is consistent with the other packages.

fix(@react-email/tailwind): Treat React as a peer dependency

---

apps/demo/package.json
packages/components/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/head/package.json
packages/react-email/package.json
packages/render/package.json
packages/tailwind/package.json
pnpm-lock.yaml

When React launched `18.3.x` we had issues due to our being dependencies
being setup in a bad way which forced me into publishing a new release for
all packages while not merging in the canary changes because of me being
unsure of their stability, so there was this weird mismatch
between versions where we had a previous canary release that was
meant to be for a later release, this PR fixes that.
This PR also bumps `render` to a canary that it wasn't on before
because of #1443. 
Here are the bumps that I did on this PR by each commit bump that
this PR does:
- **chore(tailwind): Bump to 0.0.17-canary.0 from 0.0.16-canary.1**
- **chore(head): Bump to 0.0.9-canary.0**
- **chore(render): Bump to 0.0.14-canary.0**
- **chore(react-email): Bump to 2.1.3-canary.0**
- **chore(react-email): Bump …

chore(components, create-email, head, react-email, render, tailwind): Bump for canary release

---

apps/demo/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/react-email/package.json
pnpm-lock.yaml

- **bump react-email to 2.1.3-canary.1**
- **chore(create-email): Bump template dependency on react-email to 2.1.3-canary.1**
- **bump create-email to 0.0.26-canary.1**

chore(react-email, create-email): Bump for secondary canary release

---

packages/react-email/.gitignore
packages/react-email/package.json
packages/react-email/src/cli/commands/.npmignore
packages/react-email/src/cli/commands/build.ts
packages/react-email/src/cli/commands/export.ts
packages/react-email/src/cli/commands/testing/.gitignore
packages/react-email/src/cli/commands/testing/__snapshots__/export.spec.ts.snap
packages/react-email/src/cli/commands/testing/emails/vercel-invite-user.tsx
packages/react-email/src/cli/commands/testing/export.spec.ts
packages/react-email/src/cli/index.ts
packages/react-email/src/utils/get-email-component.ts
packages/react-email/src/utils/render-resolver-esbuild-plugin.ts
pnpm-lock.yaml

This is meant for https://github.com/resend/react-email/issues/649#issuecomment-2112860431. 
The issue causing it to fail was the same one causing `email dev` to fail in the same way, and this fixes it using the same esbuild plugin approach as #1431.

fix(react-email): Export failing when using hooks

---

apps/demo/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/react-email/package.json
pnpm-lock.yaml

- **react-email: 2.1.3-canary.1 -> 2.1.3-canary.2**
- **bump create-email template dependency on react-email to 2.1.3-canary.2**
- **create-email: 0.0.26-canary.1 -> 0.0.26-canary.2**

chore(create-email, react-email): Bump for canary release

---

packages/react-email/package.json
packages/react-email/src/actions/get-email-path-from-slug.ts
packages/react-email/src/cli/utils/preview/hot-reloading/create-dependency-graph.spec.ts
packages/react-email/src/cli/utils/preview/hot-reloading/create-dependency-graph.ts
packages/react-email/src/cli/utils/preview/hot-reloading/get-imported-modules.spec.ts
packages/react-email/src/cli/utils/preview/hot-reloading/get-imported-modules.ts
packages/react-email/src/cli/utils/preview/hot-reloading/setup-hot-reloading.ts
pnpm-lock.yaml

A bit of time ago I got to implementing an improvement to the preview
server that made it hot reload when there were changes made to the dependencies.
I did this through a sort of dependency graph that connects each module to its
dependents and to its dependencies. This was very useful because it made it so that
it was both easy to update the dependency graph in an optimal way, while still
being easy to resolve through the dependents and notify the Next app 
that they changed.
The initial implementation I made though, presented a few issues. Not necessarily
in the way I did it, but a few bugs have arisen as mentioned from https://github.com/resend/react-email/issues/1366#issuecomment-2042762918 onwards.
The bugs were, in summary:
- An error, saying that the email template could not be …

fix(react-email): hot reloading rough edges

---

packages/tailwind/src/__snapshots__/tailwind.spec.tsx.snap
packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/utils/css/media-queries/separate-media-queries-from-css.spec.ts
packages/tailwind/src/utils/css/media-queries/separate-media-queries-from-css.ts

This is meant for #1450. There, they pointed out that utilities like
`max-sm:text-red-600` were not working. The reason being that it used a bit
more complex media queries than our regex accounted for:
https://github.com/resend/react-email/blob/2fc5b0df0731bafeb86ca5b5939c7af7a2d5647c/packages/tailwind/src/utils/css/media-queries/separate-media-queries-from-css.ts#L7-L11
The new regex both allows for nesting, and it doesn't necessarily check to see
if the media query is valid, like we did with the selector and the checking of
to see if there is an actual condition inside. This new regex is much more
optimal and more focused into actually separating the media queries.

fix(tailwind): Relatively complex media queries not being parsed properly

---

apps/docs/components/tailwind.mdx

This part of the documentation was not clear enough to help users by guiding
them to change their config, and it read in a way that would get users
frustrated.
The reason we don't convert `rem` to `px` is because we are trying to avoid
doing “magical” behavior, and want our component to work as well as it can with
Tailwind's intellisense, so, our recommendation to deal with this issue is to
override the `rem` unit with `px` from the Tailwind configuration.
This PR both makes it clearer that we can't apply the configuration for them
ourselves, instead of making it sound like we don't want to. It also adds in a
starting point users can go to so that they have their Tailwind configured
properly without issues.

fix(docs): Unclear mention of `rem` to `px` conversion on Tailwind page

---

packages/react-email/package.json
packages/react-email/src/utils/render-resolver-esbuild-plugin.ts
packages/render/src/render-async.ts
pnpm-lock.yaml

The day we released the `2.1.3` version of `react-email` someone from Discord
tried upgrading and noticed an error, similar to the following:
At first, I didn't think it was an actual issue on our side, but maybe some
intermittent problem on their side, probably caused by something they did wrong.
But after someone else reported the same issue, I started looking a bit deeper.
From the error, it is visible that this is something to do with `esbuild`,
specifically, it's saying that the regex of a path is invalid. The place where
we pass a regex onto `esbuild` is exactly here:
https://github.com/resend/react-email/blob/17cbc5347769826092443541822efdf05c470642/packages/react-email/src/utils/render-resolver-esbuild-plugin.ts#L13-L20
This function is a `esbuild` plugin meant to add an extra …

fix(react-email): Windows issue with the render resolving esbuild plugin

---

packages/react-email/src/utils/static-node-modules-for-vm.ts

This PR adds the necessary native Node.js modules that the Prisma client uses internally. Without these, the react-email preview server errors out.
More details on the Discord server [here](https://discord.com/channels/1022242959736983613/1246089315142860934/1246089315142860934).

fix(react-email): Add Node.js dependencies used by Prisma client

---

package.json
packages/components/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/react-email/package.json
packages/render/package.json
pnpm-lock.yaml

- **bump react-email 2.1.4 -> 2.1.5-canary.0**
- **bump render 0.0.15 -> 0.0.16-canary.0**
- **bump components dependency on render to 0.0.16-canary.0**
- **bump components 0.0.19 -> 0.0.20-canary.0**
- **bump create-email template dependency on components to 0.0.20-canary.0**
- **bump create-email template dependency on react-email to 2.1.5-canary.0**
- **update lockfile**

chore(components, create-email, react-email, render): Bump for canary release

---

apps/docs/integrations/aws-ses.mdx
apps/docs/integrations/mailersend.mdx
apps/docs/integrations/nodemailer.mdx
apps/docs/integrations/plunk.mdx
apps/docs/integrations/postmark.mdx
apps/docs/integrations/resend.mdx
apps/docs/integrations/scaleway.mdx
apps/docs/integrations/sendgrid.mdx

Previously, every integrations in the documentation, step 1, recommended to install a list of dependencies to have a particular integration work seamlessly. But that step missed the following dependency ```@react-email/render``` in each integration, which can lead to a misunderstanding when an error will show up
This PR adds the relevant imports to make the integrations work as intended. It's a fix for #1501

fix(docs): add imports for react-email in integrations step 1

---

packages/body/src/body.tsx
packages/button/src/button.tsx
packages/code-block/src/code-block.tsx
packages/code-inline/src/code-inline.tsx
packages/column/src/column.tsx
packages/container/src/container.tsx
packages/head/src/head.tsx
packages/hr/src/hr.tsx
packages/html/src/html.tsx
packages/img/src/img.tsx
packages/link/src/link.tsx
packages/markdown/src/markdown.tsx
packages/preview/src/preview.tsx
packages/row/src/row.tsx
packages/section/src/section.tsx
packages/text/src/text.tsx

Our rendering utility is meant to be optional. This comes from our apparent philosophy. Things should be flexible and minimal, from where I see it.
If we are to act on that idea, we need to pay attention to something that is in a few use cases crucial for users: being able to use `ref`s with our components. 
Not forwarding them means that we don't really support all kinds of rendering, but only the static ones.
If the user intends to build something for themselves that is meant to render the email
components in the browser itself with reactivity we shouldn't have something opposing them.
That is not to say that having the `ref`s here is not confusing, but I'd like to argue that 
it is going to be very hard to come across the `ref` unless the user actually wants it
because of all the …

chore: Add forward ref to all relevant components

---

packages/components/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/react-email/package.json
packages/render/package.json
pnpm-lock.yaml

- **react-email 2.1.5-canary.0 -> 2.1.5**
- **render 0.0.16-canary.0 -> 0.0.16**
- **render in components 0.0.16-canary.0 -> 0.0.16**
- **components 0.0.20-canary.0 -> 0.0.20**
- **bump template dependencies**
- **create-email 0.0.28-canary.0 -> 0.0.28**
- **update lock**

chore(components, create-email, react-email, render): Bump for stable release

---

packages/code-block/package.json
packages/code-block/src/code-block.tsx
packages/components/package.json
pnpm-lock.yaml

The rough edges this PR tries to correct are:
- Lines were being split in a way that empty lines were ignored
- There was an extra margin in between each code block line
- Lines, when being forced to wrap, would sometimes collapse on others
- The width of the code block was always the size of the screen
This does improve the code block quite a bit from before, and it should now
behave much more properly. Most of the issues were also coming from mobile,
because of its small screen size.
Also, with the purposes of testing, this PR also bumps the code block package
to a canary and I published it yesterday. It is
`@react-email/code-block@0.0.5-canary.0`.

fix(code-block): line-height, wrapping, width and splitting issues

---

packages/code-block/package.json
packages/components/package.json
packages/create-email/package.json
packages/create-email/template/package.json

- **code-block 0.0.5-canary.2 -> 0.0.5**
- **components 0.0.20 -> 0.0.21**
- **create-email 0.0.28 -> 0.0.29**
- **create-email template components 0.0.20 -> 0.0.21**

chore(code-block, components, create-email): Bump for stable release

---

packages/react-email/src/actions/get-emails-directory-metadata.ts
packages/react-email/src/cli/commands/export.ts

Meant for #1386. 
The issue was that we were reading all of the email template filenames from the
directory while also removing the suffixing file extension. This ended up
making `esbuild` treat all of them as the same file for some reason. This PR
just plain adds an option to not remove the file extensions, and then passes it
as true when finding the email templates to export.

fix(react-email): Export failing when templates have different suffixes

---

packages/preview/src/preview.tsx
packages/react-email/src/cli/utils/preview/hot-reloading/create-dependency-graph.ts
packages/react-email/src/cli/utils/preview/hot-reloading/setup-hot-reloading.ts

This is intended to fix the issue mentioned in https://github.com/resend/react-email/issues/1433#issuecomment-2177515290.
The issue there was that the live refresh was not notifying the preview server
when the user modified an email template dependency that was outside their
specified emails directory. What was causing this, was that our `chokidar` file watcher
was not including any files outside the users' emails directory.
To fix this, I first attempted finding the highest up file among all in the dependency graph
and adding that into the watcher. This was not the best option because it would end up
watching a bunch of files, except for the ones that we really need to.
The second attempt was to individually add in all the files into the watcher that
are specifically outside the user's …

fix(react-email): Live refresh not working with files outside of emails directory

---

.changeset/new-coats-cover.md
.changeset/orange-plums-double.md
packages/react-email/src/components/tooltip-content.tsx

**Changes Made**
Set the tooltip content text color to white, ensuring consistency and visibility across all browsers.
**Fixes**
This pull request addresses issue https://github.com/resend/react-email/issues/1326.

fix(react-email): Text color in tooltips

---

.changeset/tame-windows-look.md
packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/utils/__snapshots__/quick-safe-render-to-string.spec.tsx.snap
packages/tailwind/src/utils/quick-safe-render-to-string.spec.tsx
packages/tailwind/src/utils/quick-safe-render-to-string.ts

While working on our new patterns, I noticed that when the email template had
`container` as text anywhere inside of it, Tailwind would add in the media
queries for the `container`. This can be problematic, as it can make things a
bit slower, but because it can add styles that are not desired by the user.
At first, I wrongly thought this was a [Tailwind
issue](https://github.com/tailwindlabs/tailwindcss/issues/14070#issuecomment-2253567340),
as it happens with anything Tailwind related, but this is just how it works
being language-agnostic.
Now for some background, we currently have a `quickSafeRenderToString` function
that renders the entirity of the React tree from the component down, with the
sole purpose of handing it to Tailwind so that it can generate the respective
CSS. This …

fix(tailwind): Unecessary style generation

---

.changeset/curly-fireants-allow.md
packages/react-email/src/cli/utils/preview/hot-reloading/get-imported-modules.ts

This PR is meant to address #1570.
For background, we generate a dependency tree by parsing email templates and
files to get their imports with the purpose of knowing what email templates to
hot reload when any file changes in the user's project. This has the side
effect of us either using some faulty regex to detect imports, or using a
full-blown parser — Babel today — so that we can properly determine what the
import sources are.
The issue that was happening then, was that we did not configure our Babel
instance so that it would support `decorators`. This PR does just that, as in
that it adds the `decorators` plugin to the `parse` function we call
internally.

fix(react-email): Decorators causing dependency tree babel parsing to fail

---

.changeset/thin-scissors-wave.md
packages/react-email/src/cli/utils/preview/hot-reloading/create-dependency-graph.ts
packages/react-email/src/cli/utils/preview/hot-reloading/setup-hot-reloading.ts

Closes #1623.
The issue was that we changed some settings that we passed onto chokidar causing it to
give paths to changed files relative to the user's directory instead of relative to the CWD of the process.
This caused that a further path manipulation failed and in turn caused the hot reloading to completely break.
We may want to think about a way to test this to avoid this kind of issue happening again without being
caught by our CI.

fix(react-email): Hot reloading

---

apps/docs/getting-started/manual-setup.mdx
apps/docs/getting-started/monorepo-setup/npm.mdx
apps/docs/getting-started/monorepo-setup/pnpm.mdx
apps/docs/getting-started/monorepo-setup/yarn.mdx

`react-email` can be installed as a dev dependency, instead of a dependency that we need to ship at runtime, thus saving bundle space. Adjust the documentation for all package managers to reflect this.
This has been mentioned initially in this issue thread: https://github.com/resend/react-email/issues/1101

docs: Move `react-email` to dev dependencies in install guides

---

apps/docs/integrations/aws-ses.mdx
apps/docs/integrations/mailersend.mdx
apps/docs/integrations/nodemailer.mdx
apps/docs/integrations/plunk.mdx
apps/docs/integrations/postmark.mdx
apps/docs/integrations/scaleway.mdx
apps/docs/integrations/sendgrid.mdx
packages/render/readme.md

Changed the docs integration examples to use the await since render now returns a `Promise<string>` and not a `string`. There are still some more changes that need to be made in the `examples/[INTEGRATION]` folder but for some reason my pnpm and the one on codespaces is unable to complete the pnpm install command

Fix(docs): add await to the integration examples in the documentation

---

.changeset/selfish-garlics-clap.md
packages/tailwind/src/utils/compatibility/css-to-jsx-style.spec.ts
packages/tailwind/src/utils/compatibility/css-to-jsx-style.ts

- **fix(tailwind): Remove use of css-float instead of float**
- **remove unecessary test**

fix(tailwind): `float-left` utility being converted to `cssFloat: "left"`

---

apps/web/src/app/components/[slug]/page.tsx
apps/web/src/app/components/get-components.tsx
apps/web/src/components/component-view.tsx
apps/web/src/components/components-view.tsx

This modifies the way of rendering components in a way that simplifies its 
maintenance and makes it a bit simpler to reason about.
What is does technically is to render the email in the `getComponents` function
in a way that removes the need for the previous `element` property, and also
moves the previous `html` property as a `code` variant also simplifying the 
type for the `code` property.
It also comes with a need to change the apparent name of the code variants
to make sure that they make proper sense as follows:
- "TSX": Plain React, without any styling
- "TSX - Tailwind CSS": React with Tailwind CSS
- "HTML": The rendered output of the component
- "TSX - Inline CSS": React with inlined styles
A note to keep in mind is that all the code variants, contain just the portion
of the code …

feat(web): Make HTML a separate copy-paste code variant

---

apps/web/package.json
apps/web/src/app/components/get-components.tsx
pnpm-lock.yaml

The issue was that we were importing `traverse` from `@babel/core` which
handled `.babelrc` config loading automatically which would use some Node
features unsupported by Webpack, like `require.extensions`. What this PR does
is simply change the place we import `traverse` from to be `@babel/traverse`
and uninstall `@babel/core` for simplicity's sake.

fix(web): Webpack warning about `require.extensions` not being supported

---

apps/web/src/components/component-code-view.tsx
apps/web/src/components/component-view.tsx
apps/web/src/components/tab-trigger.tsx
apps/web/src/hooks/use-stored-state.ts

This modifies the structure of the code a bit so that the components are reused
a bit better. It also makes it so that the way of changing between React and
pure HTML is by a secondary tab that appears in the code view. With that, only
when the React tab is open, that the code variant Select is allowed to show and
be changed.
This also allows for us to separate the code variant and the selected language
in local storage for a bit better UX.

feat(web): Improved way of switching to pure HTML

---

packages/react-email/build-preview-server.mjs

This PR addresses compatibility issues with the build process on Windows systems by adding support for Windows-specific executables. Previously, the build script utilized the Unix-like `next` executable, which isn't compatible with Windows environments. This fix ensures that the correct executable (`next.cmd`) is used based on the operating system.
- Updated `build-preview-server.mjs` to detect the operating system.
- Utilized `next.cmd` for Windows and `next` for Unix-like systems.
- Ensured proper handling of build artifacts across different environments.
Developers using Windows encountered errors when attempting to run the build process due to the incorrect executable being invoked. This fix ensures a seamless build experience across all major operating systems.
- **Windows:**
- Ran …

fix(react-email): Add Windows support for build process

---

.changeset/wise-suits-run.md
packages/tailwind/copy-tailwind-types.mjs
packages/tailwind/package.json
packages/tailwind/vite.config.ts
pnpm-lock.yaml

This addresses #1616.
The problem is that since we are bundling Tailwind, there is no real need for
having it as a proper dependency which would lead to bigger install times.
Having it as dev dependency ended up causing the type `TailwindConfig` to not
be properly created, as in it that it would not properly define inner
properties unless the user had `tailwindcss` installed themselves on the
project.
The solution for this is to bundle in the types from Tailwind and use them on
our exported types, instead of importing them from the possibly not installed
`tailwindcss`.
The first attempt at doing this was by going for the `bundledPackages` option
for the `vite-plugin-dts` package which ended up with errors due to very complex
types inside `tailwindcss`.
The final solution was to simply …

fix(tailwind): TailwindConfig type broken when `tailwindcss` is not installed

---

.changeset/silly-knives-kiss.md
packages/code-block/src/code-block.tsx

The issue that was happening was that the size of the line numbers's span was
changing based on the size of its content. As we were setting the distance
between the line number and the code block's content, that caused the actual
content of the code block to get unaligned when going from lines with fewer to
more digits.

fix(code-block): Improper padding on the line numbers

---

.changeset/cuddly-meals-sniff.md
.pnpmfile.cjs
packages/body/package.json
packages/button/package.json
packages/code-block/package.json
packages/code-inline/package.json
packages/column/package.json
packages/components/package.json
packages/container/package.json
packages/font/package.json
packages/head/package.json
packages/heading/package.json
packages/hr/package.json
packages/html/package.json
packages/img/package.json
packages/link/package.json
packages/markdown/package.json
packages/preview/package.json
packages/render/package.json
packages/row/package.json
packages/section/package.json
packages/tailwind/package.json
packages/text/package.json
pnpm-lock.yaml

This PR is meant to be merged just on canary and released for testing on real situations
as to ensure that we are not going to get peerDependencies errors. If this ends up causing 
issues that we can't really get around, and ends up becoming something we don't want
we'll just revert and the next releases are going to be without this.

chore(all): Move React dependencies to just plain dependencies

---

.changeset/large-taxis-smoke.md
packages/react-email/src/cli/commands/testing/__snapshots__/export.spec.ts.snap
packages/render/package.json
packages/render/src/shared/utils/pretty.ts
pnpm-lock.yaml

This is a no-brainer decision for four reasons:
1. Prettier is much more well maintained
2. Prettier's standalone is smaller than `js-beautify`
3. Prettier does not force us to do weird finagling to work with ESM and CJS
4. Prettier's formatting is much prettier

feat(render): Use prettier's standalone API instead of js-beautify

---

.changeset/shaggy-beers-leave.md
packages/code-block/src/code-block.tsx
packages/code-block/src/languages-available.ts
packages/tailwind/readme.md

Hi there!
I noticed there is a little typo in the source code while using the code-block component. You wrote **PrismLangauge** instead of **PrimsLanguage**

fix(code-block): Typo "PrismLanguage"

---

.changeset/purple-feet-share.md
packages/react-email/src/actions/get-email-path-from-slug.ts
packages/react-email/src/actions/get-emails-directory-metadata.ts
packages/react-email/src/actions/render-email-by-path.tsx
packages/react-email/src/app/preview/[...slug]/page.tsx
packages/react-email/src/app/preview/[...slug]/preview.tsx
packages/react-email/src/contexts/emails.tsx
packages/react-email/src/hooks/use-email-rendering-result.ts
packages/react-email/src/hooks/use-rendering-metadata.ts

The problem that was happening was something like this
https://github.com/user-attachments/assets/186fdf16-720c-424a-9653-2b9cc1945169
Every time the user navigated, even if it was to the same page already open, it would always re-render the email template, even if it was already rendered. When we first implemented the current architecture for the preview server, with Next.js 14, RSCs would always be cached in such a way that this navigation wouldn't re-render the RSC for the `/preview/[slug]` page, but as of Next.js 15 this does not seem to be the case.
The solution I chose for this was to store a cache for rendered emails in the server instead of in the client, this allows for the `renderEmailByPath` to return the cache when navigating across pages but also leads to less code and easier …

fix(react-email): Unwanted email re-renders when switching templates

---

.changeset/early-mugs-divide.md
packages/react-email/src/cli/utils/preview/start-dev-server.ts

https://github.com/resend/react-email/commit/7eb68af95681600545ce992b03ff58f2ace9fb24#diff-c5c5ee3ee563e33630e1ad83f07d66cb99b9be9a662fa8f4f9d7a6d43e98b7d0
This commit caused `NODE_ENV` to no longer be respected and always become `development`
This change will respect `NODE_ENV` and default to `development` if nothing is passed in.

fix(react-email): Respect user NODE_ENV

---

packages/react-email/src/cli/utils/preview/start-dev-server.ts
packages/tailwind/src/utils/css/resolve-all-css-variables.ts

This PR fixes to use optional chain

fix(all): Use optional chain

---

.changeset/chilly-donkeys-worry.md
packages/react-email/src/cli/commands/testing/__snapshots__/export.spec.ts.snap
packages/react-email/src/components/sidebar/sidebar-directory-children.tsx
packages/render/src/shared/utils/__snapshots__/pretty.spec.ts.snap
packages/render/src/shared/utils/pretty.spec.ts
packages/render/src/shared/utils/pretty.ts

The issue was that, for some reason, Prettier's HTML printer inserts the ending `</span` manually
when printing the `if mso` comment, and that ending tag was not being inserted on our side. It also
seems to be inserted under some obscure conditions that would be way too hard for us to replicate.
https://github.com/prettier/prettier/blob/3e2f487049eff356bb7c766cfc40a7088019d3f6/src/language-html/print/tag.js#L42-L53
The solution I opted into was to run the original printing function, and then do our required changes
on Prettier `Doc`s. The changes were to simply map recursively through the entire returned `Doc` and convert
all `line` `Doc`s to either a space or nothing based on whether it is a soft line or not.

fix(render): `pretty` option including extra `<` in the `Button`

---

.changeset/bright-chicken-learn.md
packages/react-email/module-punycode.d.ts
packages/react-email/package.json
packages/react-email/src/utils/static-node-modules-for-vm.ts
pnpm-lock.yaml

chore(react-email): Use the `punycode` package for the static node modules

---

packages/react-email/src/cli/commands/build.ts
packages/react-email/src/cli/utils/preview/start-dev-server.ts

Hi, I was analyzing the CLI code and found a typo, so I fixed it.
- `cliPacakgeLocation` => `cliPackageLocation`

fix(cli): Correct typo in cliPacakgeLocation to cliPackageLocation

---

.changeset/shy-fans-allow.md
packages/react-email/src/utils/get-emails-directory-metadata.ts
packages/react-email/src/utils/js-email-detection.spec.ts
packages/react-email/src/utils/testing/js-email-export-default.js
packages/react-email/src/utils/testing/js-email-test.js
packages/react-email/src/utils/testing/mdx-email-test.js

The React Email preview tool was not correctly displaying `.js` files in the preview, despite the code explicitly including `.js` in the list of supported file extensions. After investigation, we discovered that the issue was in the email detection logic, which was only checking for ES6 `export default` syntax, missing other common JavaScript export patterns.
Enhanced the `isFileAnEmail` function in `get-emails-directory-metadata.ts` to detect three different export patterns:
1. ES6 export default syntax: `export default Component`
2. CommonJS module exports: `module.exports = Component`
3. Named exports (used in MDX-generated files): `export { Component as default }`
- Added regex patterns to detect each export style
- Created comprehensive tests to verify the behavior with different …

fix(react-email):  Detection of files with various export patterns

---

package.json
packages/render/package.json
pnpm-lock.yaml

Resolves https://github.com/resend/react-email/issues/1910

chore(deps): upgrade prettier to 3.5.3

---

packages/react-email/src/utils/caniemail/tailwind/get-tailwind-config.ts

This does indeed add the support for importing modules inside separate `tailwind.config` files, but it's required to be a separate file. If it isn't in a separate file, the code inside `config` is copied and ran with `new Function(...)` without any dependencies, if it has some. While the config file is bundled this inlined config is not, meaning it is kind of a limitation.
Fixes one of the problems in #2025

fix(react-email): Module importing for separate tailwind configs

---

apps/demo/package.json
packages/components/package.json
packages/create-email/package.json
packages/react-email/package.json
packages/react-email/src/cli/commands/build.ts
pnpm-lock.yaml

This PR also improves the reliability of the initial `pnpm install` by using the `prepare` script on `react-email` and `@react-email/components` to build them both as they are needed on other packages. The initial `pnpm install` still shows a warning, but it does work after just `pnpm install` on a fresh clone.
This PR also adds in a dev dependency for `create-email` on `react-email` and `@react-email/components` so that dependencies are properly resolved there in `turbo test`.

feat(root): Improved reliability on first install

---

.changeset/fifty-streets-kick.md
packages/react-email/src/utils/caniemail/tailwind/get-tailwind-config.ts

Before this PR, we tried to find the config assuming that the import specifier was a proper path, but it could also be using a path alias, so this PR fixes that by offloading the work to find the proper path to esbuild through defining a virtual file that imports with the same import specifier.

fix(react-email): Linter not being able to handle tailwind config import with path alias

---

packages/create-email/template/emails/vercel-invite-user.tsx

fix(create-email): linter

---

apps/web/src/app/api/check-spam/__snapshots__/check-spam.spec.tsx.snap
apps/web/src/app/api/check-spam/check-spam.spec.tsx

This PR removes the papermark spam checking test, as it seems to be giving off different results from time to time.

chore(web): Improve stability of checkSpam test

---

.changeset/eleven-wombats-make.md
packages/react-email/src/cli/utils/preview/hot-reloading/setup-hot-reloading.ts
packages/react-email/src/hooks/use-email-rendering-result.ts
packages/react-email/src/utils/contains-email-template.spec.ts
packages/react-email/src/utils/contains-email-template.ts
packages/react-email/src/utils/get-email-component.ts
packages/react-email/src/utils/get-emails-directory-metadata.ts

Meant for #2078.
The main problem was that the component was being treated as an email template on the hot reloading code which is then fixed with
https://github.com/resend/react-email/blob/fe84d5c2de8cd8d61d87dcfd713c343f0dc2f50f/packages/react-email/src/hooks/use-email-rendering-result.ts#L32-L36
Alongside a unit test to ensure this function works as intended. This PR also ends up fixing the error in https://github.com/resend/react-email/issues/1872#issuecomment-2773299339

fix(react-email): Dependents of dependents of email templates not causing hot reloads 

---

.changeset/wet-planes-camp.md
packages/react-email/src/utils/get-email-component.ts

This PR adds a proper error message for when the user doesn't have a default exported function on their email template

fix(react-email): No error with missing default function export

---

package.json
packages/create-email/package.json
packages/create-email/src/index.js
packages/create-email/src/index.spec.ts
packages/create-email/template/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

This completely unties the version of other packages from the starter, as it just fetches off from the given tag. The new usage is something like
```bash 
npx create-email --tag latest/canary/alpha
```
With `latest` being used as default when `--tag` is not provided.

feat(create-email): Use latest from specified tag for `react-email` and `@react-email/components`

---

.changeset/strong-peas-kneel.md
apps/docs/utilities/render.mdx
apps/web/components/ensure-matching-variants.spec.tsx
apps/web/src/app/components/get-imported-components-for.tsx
packages/react-email/src/actions/render-email-by-path.tsx
packages/react-email/src/cli/commands/export.ts
packages/react-email/src/cli/commands/testing/export.spec.ts
packages/react-email/src/cli/index.ts
packages/react-email/src/utils/esbuild/renderring-utilities-exporter.ts
packages/react-email/src/utils/get-email-component.ts
packages/render/src/browser/index.ts
packages/render/src/browser/render.tsx
packages/render/src/node/index.ts
packages/render/src/node/render.tsx
packages/render/src/shared/options.ts

Compliment to the feature request https://github.com/resend/react-email/discussions/1905
This takes the call to `pretty` out of the render functions and exports it separately. The new usage is `const html = await pretty(await render(<MyTemplate/>));`
One test is failing, and I'm a bit stumped. By throwing the exception on line 142 of export.ts, I was able to get this error message. I've done what I can to pipe it through the custom import faker, not sure what's wrong.
```
FAIL  src/cli/commands/testing/export.spec.ts > email export
TypeError: emailModule.pretty is not a function
❯ Module.exportTemplates src/cli/commands/export.ts:128:76
126|         options,
127|       );
128|       if (!options.plainText && shouldPretty) rendered = await emailModule.pretty(rendered);
| …
```

feat(render): Separate pretty from render

---

.changeset/famous-years-knock.md
packages/react-email/src/actions/render-email-by-path.tsx
packages/react-email/src/cli/commands/export.ts
packages/react-email/src/hooks/use-email-rendering-result.ts
packages/react-email/src/utils/esbuild/renderring-utilities-exporter.ts
packages/react-email/src/utils/get-email-component.ts

- **chore(react-email): Use deprecated `pretty` to allow for backwards-compatibility for now**

chore(react-email): Use deprecated `pretty` to allow for backwards-compatibility for now

---

.changeset/honest-paws-wash.md
packages/react-email/package.json
packages/react-email/src/cli/commands/export.ts
pnpm-lock.yaml

This was an error happening when running `email dev`. After building without minification and trying to run it with yalc in a starter project the error was 
```js
⨯ TypeError: createServerParamsForMetadata is not a function
at resolveMetadataItemsImpl (.yalc/react-email/dist/preview/.next/server/chunks/775.js:19324:20)
at <unknown> (.yalc/react-email/dist/preview/.next/server/chunks/775.js:19302:12)
at resolveMetadata (.yalc/react-email/dist/preview/.next/server/chunks/775.js:19572:33)
at renderMetadata (.yalc/react-email/dist/preview/.next/server/chunks/775.js:13601:73)
at getResolvedMetadataImpl (.yalc/react-email/dist/preview/.next/server/chunks/775.js:13583:12)
at metadata (.yalc/react-email/dist/preview/.next/server/chunks/775.js:13491:16)
at resolveFinalMetadata …
```

fix(react-email): "createServerParamsForMetadata is not a function"

---

.changeset/breezy-planes-attend.md
packages/react-email/src/cli/utils/preview/start-dev-server.ts

fix(react-email): No explicit error when running with Node <= 17

---

.changeset/itchy-moles-give.md
packages/react-email/src/utils/contains-email-template.spec.ts
packages/react-email/src/utils/contains-email-template.ts

fix(react-email): Hot reloading with directories two or more levels deep

---

packages/preview-server/src/actions/email-validation/check-compatibility.ts

I stomped on this typo while I was working on another thing
From `Categroy` to `Category`

FIX: fix(types): correct typo in SupportEntryCategory type

---

README.md

Without running the build command first, dev didn't work the first time.
The docs already mention building and running, but with my suggestion, it's easier to copy and paste the exact commands. It's also a bit more explicit, which helps avoid confusion.

docs(readme): split build and run instructions for clarity

---

.changeset/common-goats-find.md
.changeset/config.json
packages/preview-server/_index.js
packages/preview-server/index.mjs
packages/preview-server/package.json
packages/react-email/src/utils/get-preview-server-location.ts

the demo deploy is failing because we haven't yet released an on-par version of `@react-email/preview-server` with the current `react-email` one

feat(react-email, preview-server): fixed equal versions for both

---

.changeset/famous-pants-cross.md
packages/react-email/src/app/layout.tsx
packages/react-email/src/components/shell.tsx

The problem was the wrapper `div` we have that didn't include the `flex-col` that we had before #2251. Another thing was the background for the floating sidebar, this PR sets the opacity of everything to 0 once the sidebar is open to give way to the gradient in the background

fix(react-email): mobile's sidebar broken in preview server

---

.changeset/kind-showers-exist.md
packages/react-email/src/utils/preview/serve-static-file.ts

https://github.com/resend/react-email/security/code-scanning/190

fix(react-email): security issue with path for static files

---

.changeset/better-insects-like.md
packages/preview-server/_index.js
packages/preview-server/src/app/preview/[...slug]/preview.tsx
pnpm-lock.yaml

fix(preview-server): forced `color-scheme: dark`

---

.github/workflows/release.yml

Sets up the automated releases workflow for all changesets coming into `main` as well. This replicates the same steps as `release-canary.yml`

feat(ci): release workflow for `main`

---

apps/docs/utilities/render.mdx

Closes #1732. I'd say that it's much better for us to recommend users to polyfill this, instead of us doing it, to avoid having the package larger for the minority of use cases, since React Email is mainly meant for running in the server for sending the email templates themselves. The use of the API is also done by `react-dom`, and they themselves do not polyfill this.

feat(docs): danger callout for running `render` on the browser

---

packages/react-email/src/utils/get-preview-server-location.ts

Closes #2341. The logs from the user were:
```zig
$ email dev
Error: Cannot find module 'next'
Require stack:
- \G:\react-email-starter\node_modules\@react-email\preview-server
at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
at Function.resolve (node:internal/modules/helpers:145:19)
at jitiResolve (G:\react-email-starter\node_modules\jiti\dist\jiti.cjs:1:187220)
at jitiRequire (G:\react-email-starter\node_modules\jiti\dist\jiti.cjs:1:189288)
at Function.import (G:\react-email-starter\node_modules\jiti\dist\jiti.cjs:1:199778)
at startDevServer (file:///G:/react-email-starter/node_modules/react-email/dist/index.js:936:55)
at async Command.dev (file:///G:/react-email-starter/node_modules/react-email/dist/index.js:1135:24) {
code: 'MODULE_NOT_FOUND',
requireStack: [ …
```

fix(react-email): path resolution done wrong for Windows

---

.changeset/kind-experts-vanish.md
packages/preview-server/src/utils/caniemail/tailwind/get-tailwind-config.spec.ts
packages/preview-server/src/utils/caniemail/tailwind/get-tailwind-config.ts
packages/preview-server/src/utils/caniemail/tailwind/tests/dummy-email-template.tsx
packages/preview-server/src/utils/caniemail/tailwind/tests/tailwind.config.ts

For background, the compatibility checker (caniemail) tries to find and get the Tailwind config defined by the user in the Tailwind element `<Tailwind config={...}>`.
Noticed that the warning from this piece of code:
https://github.com/resend/react-email/blob/b2407a1156d0251cfe466a159306c47d3bcfcfae/packages/preview-server/src/utils/caniemail/tailwind/get-tailwind-config.ts#L66-L69
was happening when building the demo, even if it doesn't fail, and I realized we could just not have this at all by just unifying the methods we have for resolving the tailwind config for the email template into bundling with esbuild.
What this pull request does is simply bundle the source code of the email template while exporting the exact source code in the expression inside the `<Tailwind config={...}>` …

fix(preview-server): compatibility checker can't find config when inlining pixel based preset

---

.changeset/calm-birds-spend.md
packages/tailwind/src/__snapshots__/tailwind.spec.tsx.snap
packages/tailwind/src/tailwind.spec.tsx
packages/tailwind/src/utils/tailwindcss/setup-tailwind.ts
packages/tailwind/src/utils/tailwindcss/tailwind-internals.d.ts

Closes #1871. The issue there is pretty clear on what the problem they were having was, the problem particularly was that the internal `candidateRuleCache` from Tailwind was not being cleared. This pull request also adds in a test to ensure that this is working and that there are no future regressions on this.
https://github.com/resend/react-email/blob/5344b1ed67b751508ae4694935f997c130ad7ec2/packages/tailwind/src/utils/tailwindcss/setup-tailwind.ts#L27-L27
The above line is the actual fix, it literally sets the cache as empty before doing any of the class-to-style resolution.
The specific issue was that the first time a class like `dark:...` (i.e., a class to insert into the user's `<Head>`), it worked just fine, but then the second time the same exact class was used again, it seems to …

fix(tailwind): media queries not getting sanitized sometimes

---

apps/docs/contributing/codebase-overview.mdx

Fixes #2391
Before (broken url) : 
https://github.com/user-attachments/assets/773d1588-c7b1-4061-b8d2-7800f38cbc03
After : 
https://github.com/user-attachments/assets/d775a0bc-926b-4390-b874-73da87de70eb

fix(docs): fix broken url in `Codebase Overview` documentation  

---

README.md
apps/docs/introduction.mdx

Fixes https://github.com/resend/react-email/issues/2052

chore(docs): update current year in `why` line

---

packages/preview-server/src/actions/render-email-by-path.tsx
packages/preview-server/src/app/preview/[...slug]/page.tsx
packages/preview-server/src/app/preview/[...slug]/preview.tsx
packages/preview-server/src/components/toolbar.tsx

After considering #1847 carefully, we've decided we're going to not provide a way to format templates anymore in the future, which will mean we'll only format the HTML for viewing in the preview server, and probably also for `email export`.
To actually deal with #1847, this changed it so that the markup used for the iframe, and for sending the email template are not formatted at all. This does fix the issue, and users should not format if they don't really need to, especially if they're sending emails which means there's going to be unnecessary overhead.
Closes #1847

chore(preview-server): use unformatted markup for sending and preview

---

.github/workflows/release-canary.yml
.github/workflows/release.yml

This reverts commit c85be9f5b38b7b1dc84d30f43479b1c32b5d364c. The new version of the action (#2400) seems to be breaking: 
https://github.com/resend/react-email/actions/runs/16677320246/job/47207463679

chore(deps): revert update of changesets/action

---

apps/docs/contributing/codebase-overview.mdx
apps/docs/contributing/development-workflow/1-setup.mdx
apps/docs/contributing/development-workflow/6-editing-the-components.mdx
apps/docs/contributing/development-workflow/6-using-the-playground.mdx
apps/docs/docs.json

This updates the contributing guide according to the new changes we made to our development workflows. For starters, it adds a mention to the new `@react-email/preview-server` package and updates the way the CLI is described in the "Codebase overview".
As for the development workflows, I updated the Setup step to include linking the [email-dev](https://github.com/resend/react-email/tree/canary/packages/react-email#setting-up-the-environment) script instead of building all the packages since most of the reasons to build all packages were needing to run the `demo` which isn't really needed anymore with the playground. 
I also added in another step to the "Development Workflow" tab called "Editing components" to explain the usage of the playground
I haven't added any mention to how to run …

feat(docs): new package mention, playground usage, simplified setup
