packages/container/.babelrc
packages/container/.eslintrc.js
packages/container/jest.config.js
packages/container/license.md
packages/container/package.json
packages/container/readme.md
packages/container/src/__snapshots__/container.spec.tsx.snap
packages/container/src/container.spec.tsx
packages/container/src/container.tsx
packages/container/src/index.ts
packages/container/tsconfig.json
yarn.lock

closes https://github.com/zenorocha/react-email/issues/11

feat(container): Add Container

---

apps/preview/readme.md

From https://discordapp.com/channels/1022242959736983613/1022242960294813738/1022942711407460423

chore(preview): Fix docs steps

---

apps/website/readme.md

From https://discordapp.com/channels/1022242959736983613/1022242960294813738/1022942711407460423

chore(website): Fix docs steps

---

apps/preview/package.json
apps/preview/src/components/vercel-invite-user.tsx
packages/code/.babelrc
packages/code/.eslintrc.js
packages/code/jest.config.js
packages/code/license.md
packages/code/package.json
packages/code/readme.md
packages/code/src/__snapshots__/code.spec.tsx.snap
packages/code/src/code.spec.tsx
packages/code/src/code.tsx
packages/code/src/index.ts
packages/code/tsconfig.json
packages/container/readme.md
readme.md

- Creation of `Code` component and package.
- Small fixes on root README and container README files

feat(code): Create `Code` component

---

packages/heading/.babelrc
packages/heading/.eslintrc.js
packages/heading/jest.config.js
packages/heading/license.md
packages/heading/package.json
packages/heading/readme.md
packages/heading/src/__snapshots__/heading.spec.tsx.snap
packages/heading/src/heading.spec.tsx
packages/heading/src/heading.tsx
packages/heading/src/index.ts
packages/heading/tsconfig.json
packages/utils/src/as.ts
packages/utils/src/index.ts

closes https://github.com/zenorocha/react-email/issues/13

feat(heading): Add Heading

---

apps/preview/package.json
apps/preview/src/pages/index.tsx

This PR replaces the current code component with the new one from the design system package and also enables the `pretty` option from render package.

feat(preview): Use new code component

---

packages/design-system/src/code/code.tsx
packages/design-system/src/icons/icon-download.tsx
packages/design-system/src/icons/index.ts
packages/design-system/tsconfig.json
yarn.lock

Adds an icon next to "Copy" to download an HTML file with the preview code 
closes #109

feat(preview): Add download preview

---

packages/utils/src/index.ts
packages/utils/src/px-to-pt.ts

Convert to `px` to `pt` util to help converting Px to Pt when supporting Outlook

feat(utils): Add `pxToPt` util

---

apps/preview/package.json
packages/code/src/code.spec.tsx
packages/pre/.babelrc
packages/pre/.eslintrc.js
packages/pre/jest.config.js
packages/pre/license.md
packages/pre/package.json
packages/pre/readme.md
packages/pre/src/__snapshots__/pre.spec.tsx.snap
packages/pre/src/index.ts
packages/pre/src/pre.spec.tsx
packages/pre/src/pre.tsx
packages/pre/tsconfig.json
readme.md

- Add `Pre` component 
- Rename `Code` test suite variable from `container` to `actualOutput` to maintain a standard between all components tests.
- Resolves #49

feat(pre): Create `Pre` component

---

apps/preview/src/components/layout.tsx
apps/preview/src/components/packages/avatar-fallback.tsx
apps/preview/src/components/packages/avatar-image.tsx
apps/preview/src/pages/packages/avatar-fallback.tsx
apps/preview/src/pages/packages/avatar-image.tsx
yarn.lock

Reverts zenorocha/react-email#149

Revert "fix(preview): Unused files"

---

packages/head/src/head.tsx

[#175](https://github.com/zenorocha/react-email/issues/157)

fix(head): Remove style prop

---

packages/head/src/head.tsx
packages/html/src/html.tsx

[#156 ](https://github.com/zenorocha/react-email/issues/156)

fix(html): Remove style prop

---

packages/react-email/source/commands/dev.ts

Fixes https://github.com/zenorocha/react-email/issues/218

fix(react-email): Cache emails

---

packages/create-email/src/index.js

Address Linux issue: https://github.com/zenorocha/react-email/issues/112#issuecomment-1359098761

fix(create-email): Remove usr bin no warnings flag

---

packages/react-email/preview/package.json
packages/react-email/preview/src/components/code.tsx
packages/react-email/preview/src/components/icon-button/icon-button.tsx
packages/react-email/preview/src/components/icon-button/index.ts
packages/react-email/preview/src/components/icons/icon-base.tsx
packages/react-email/preview/src/components/icons/icon-check.tsx
packages/react-email/preview/src/components/icons/icon-clipboard.tsx
packages/react-email/preview/src/components/icons/icon-download.tsx
packages/react-email/preview/src/components/icons/index.ts
packages/react-email/preview/src/components/tooltip/index.ts
packages/react-email/preview/src/components/tooltip/tooltip-content.tsx
packages/react-email/preview/src/components/tooltip/tooltip.tsx
packages/react-email/preview/src/pages/_app.tsx
packages/react-email/preview/src/pages/preview/[slug].tsx
packages/react-email/preview/src/utils/copy-text-to-clipboard.ts
packages/react-email/preview/src/utils/index.ts
packages/react-email/preview/yarn.lock

feat(react-email): Bring back buttons to download and copy to clipboard

---

packages/react-email/preview/src/pages/preview/[slug].tsx

Reverts zenorocha/react-email#276

Revert "fix(react-email): Syntax error"

---

packages/section/src/__snapshots__/section.spec.tsx.snap
packages/section/src/section.spec.tsx
packages/section/src/section.tsx

This PR adds a condition that checks for the children of the `Section` component and adds `td` tags whenever a child isn't valid and isn't a `Column` component.

feat(section): `Section` component provides td tag

---

apps/docs/components/column.mdx

Fixing a html typo in the docs

Fix typo in column.mdx

---

apps/docs/components/column.mdx

This PR fixes Column component example closing tags

fix(docs): column component closing tag

---

packages/react-email/preview/src/components/send.tsx

feat(react-email): Add powered by Resend

---

packages/render/package.json

chore(render): Lower required Node version

---

apps/demo/.gitignore
packages/render/src/render.ts
yarn.lock

This PR exports the `Options` to be used in `react-email`

feat(render): Export options

---

apps/demo/package.json
yarn.lock

This PR upgrades the react-email to 1.6.2

chore(demo): Upgrade react email

---

packages/react-email/preview/package.json
packages/react-email/preview/src/pages/preview/[slug].tsx
packages/react-email/preview/src/utils/language-map.ts
packages/react-email/preview/yarn.lock

Adds a new plain text tab to preview app
Related #343

feat: Show plain text result in another tab

---

packages/container/src/container.tsx
packages/html/src/html.tsx

Hi, guys! what's up?
Adding rest props and ref to the principal div element

fix(container, html): Missing props

---

apps/demo/emails/airbnb-review.tsx

fix(demo): Airbnb review typo

---

packages/html/.babelrc
packages/html/jest.config.js
packages/html/package.json
packages/html/src/__snapshots__/html.spec.tsx.snap
packages/html/src/html.spec.tsx

I realized that we didn't have tests on this component, so I decided to add it. Makes sense?

feat(html): Add HTML tests

---

apps/docs/integrations/aws-ses.mdx
apps/docs/integrations/nodemailer.mdx
apps/docs/integrations/overview.mdx
apps/docs/integrations/postmark.mdx
apps/docs/integrations/sendgrid.mdx

In this PR, I added documentation about how you can utilise babel to integrate React Email into your NodeJS application. I also updated the imports to match the `export default` props

chore(docs): Document integration with NodeJS

---

packages/react-email/preview/package.json
packages/react-email/preview/src/components/code-container.tsx
packages/react-email/preview/src/components/icon-button.tsx
packages/react-email/preview/src/components/sidebar.tsx
packages/react-email/preview/src/components/topbar.tsx
packages/react-email/preview/yarn.lock

https://user-images.githubusercontent.com/398893/213109672-b366392e-cc8b-4ced-88fb-ad3bf5429ec9.mp4

feat(react-email): Add hover effects

---

apps/docs/cli.mdx

Docs to support https://github.com/resendlabs/react-email/pull/384

feat(docs): Add documentation for --dir option

---

packages/react-email/package.json
packages/react-email/source/commands/dev.ts

Fix for dev server not starting. For stack trace or more info, see #417 
Closes #417

fix(react-email): Dev server command

---

apps/docs/components/tailwind.mdx
apps/docs/mint.json
packages/tailwind/readme.md

In this PR, I added documentation about how to use the Tailwind component.
Fixes: https://github.com/resendlabs/react-email/issues/415

chore(docs): Document Tailwind Component

---

readme.md

feat(root): Add link to the contributions page

---

packages/create-email/template/readme.md

Hello 👋, Firstly thank you for the great project it really solves a big hassle for us 
In this pr I just updated the template readme to indicate the real port that will be used in development

chore(root): Update template port is 3000

---

packages/create-email/package.json
packages/create-email/template/package.json
packages/create-email/template/yarn.lock
packages/row/src/row.tsx

Add missing dependencies for create-email package.
closes https://github.com/resendlabs/react-email/issues/475

fix(create-email): Missing dependencies

---

apps/demo/emails/stack-overflow-tips.tsx

Header content is not aligned using rows and columns

fix(demo): Broken layout in stackoverflow demo

---

apps/docs/components/button.mdx
apps/docs/components/column.mdx
apps/docs/components/container.mdx
apps/docs/components/font.mdx
apps/docs/components/head.mdx
apps/docs/components/heading.mdx
apps/docs/components/hr.mdx
apps/docs/components/html.mdx
apps/docs/components/image.mdx
apps/docs/components/link.mdx
apps/docs/components/preview.mdx
apps/docs/components/section.mdx
apps/docs/components/tailwind.mdx
apps/docs/components/text.mdx
apps/docs/getting-started/automatic-setup.mdx
apps/docs/getting-started/manual-setup.mdx
apps/docs/integrations/aws-ses.mdx
apps/docs/integrations/mailersend.mdx
apps/docs/integrations/nodemailer.mdx
apps/docs/integrations/overview.mdx
apps/docs/integrations/postmark.mdx
apps/docs/integrations/resend.mdx
apps/docs/integrations/sendgrid.mdx
apps/docs/utilities/render.mdx

This PR adds `pnpm` to all the installations snippets inside `CodeGroups`

docs(CodeGroup): add pnpm option

---

packages/components/package.json
packages/components/src/index.ts

This PR adds the Tailwind component to the components package.

feat(components): Add Tailwind

---

packages/body/package.json
packages/body/src/body.tsx
packages/button/package.json
packages/button/src/button.tsx
packages/button/src/utils/index.ts
packages/button/src/utils/px-to-pt.ts
packages/column/package.json
packages/column/src/column.tsx
packages/container/package.json
packages/container/src/container.tsx
packages/head/package.json
packages/head/src/head.tsx
packages/heading/package.json
packages/heading/src/heading.tsx
packages/heading/src/utils/as.ts
packages/heading/src/utils/index.ts
packages/heading/src/utils/spaces.ts
packages/hr/package.json
packages/hr/src/hr.tsx
packages/img/package.json
packages/img/src/img.tsx
packages/link/package.json
packages/link/src/link.tsx
packages/row/package.json
packages/row/src/row.tsx
packages/section/package.json
packages/section/src/section.tsx
packages/text/package.json
packages/text/src/text.tsx

This PR adds `data-id` attribute to the packages components.

feat(packages): Add `data-id`

---

demo/package.json
demo/yarn.lock

This PR upgrades the `demo` package to use the latest `@react-email/components`.

chore(demo): Upgrade `@react-email/components`

---

docs/changelog.mdx

This PR adds the latest changelog to the docs

chore(docs): Add latest changelog

---

packages/react-email/package.json
packages/react-email/yarn.lock

Bump `react-email` to `v1.8.0-canary.2`

chore(react-email): Bump to `v1.8.0-canary.2`

---

web/package.json
web/src/pages/_app.tsx
web/yarn.lock

Fix: This change resolves #558 by removing @next/font error

fix(web): `@next/font` warning

---

packages/react-email/.gitignore
packages/react-email/.npmignore

chore(react-email): Ignore files

---

packages/react-email/source/commands/dev.ts

This PR throws an error when missing `emails` folder.

fix(react-email): Handle error when missing `emails` folder

---

packages/react-email/package.json

This PR removes unused scripts commands

chore(react-email): Remove scripts commands

---

client/src/components/sidebar.tsx

This pr resolves #601 by removing extra class

fix(client): Remove nav `block` classname

---

packages/react-email/source/utils/start-server-command.ts

Fixes #511 by killing all subprocesses if the main process is exiting.

fix(client): kill subprocess if an error occurs

---

packages/create-email/src/index.js

fixes https://github.com/resendlabs/react-email/issues/612

fix(create-email): Required node

---

docs/changelog.mdx

feat(docs): Add new changelog entry

---

packages/components/package.json
packages/components/yarn.lock

chore(components): Upgrade `@react-email/tailwind`

---

client/src/app/preview/[slug]/page.tsx

fix(client): Lint

---

packages/body/package.json
packages/tailwind/package.json
yarn.lock

This PR adds the `@babel/core` peer dependency to the `body` and `tailwind` components to remove errors during `yarn` install process.

fix: add @babel/core to `body` and `tailwind` components to avoid yarn errors

---

packages/react-email/source/utils/generate-email-preview.ts

fixes #667 
Thanks for @sebastianbassen for providing the dev environment via screenshare and his glob-bug expertise

fix(client): Support for windows when generating template files

---

demo/emails/vercel-invite-user.tsx

usage of invitedByUsername in vercel invite demo mail

fix(demo): Use `invitedByUsername` prop

---

docs/components/markdown.mdx
docs/mint.json

- Updated documentation for markdown compoonent
- Added to markdown to component section in sidebar

feat(docs): Updated docs for markdown package

---

client/package.json
client/yarn.lock
web/package.json
web/yarn.lock

update next.js to a newer version to fix this [issue](https://github.com/resendlabs/react-email/issues/649) which is related to a bug in next.js that has been fixed in newer versions

chore(client, web): Update Next.js dependency

---

demo/emails/amazon-review.tsx
demo/emails/netlify-welcome.tsx

- Fix for typo in height in `amazon-review` email template
- Fix for wrong syntax for rendering jsx elements from object in `netlify-welcome` email template

fix(demo): Errors in example email templates

---

packages/markdown/package.json
packages/markdown/src/markdown.spec.tsx
packages/markdown/src/markdown.tsx

**This is a fix for issue #716.**
The problem was JSX was being injected as valid HTML. 
It was an oversight and has been fixed now.

chore(markdown): Upgrade `md-to-react-email` dependency

---

client/src/app/home.tsx
client/src/app/preview/[slug]/preview.tsx
client/src/components/shell.tsx
client/src/components/sidebar.tsx
client/src/components/topbar.tsx

This PR contains code changes to improve usability of the client on devices with smaller screens. 
It contains:
- A new header with the project branding and nav toggle
- The collapsible menu now takes full screen width on mobile devices
- The collapsible menu can now to be opened and close on smaller screen sizes
- The preview section now takes up full width on smaller screen sizes
- The title is now set to show on only larger screens as it clutters the top bar section

fix(client): Improve responsive

---

packages/column/src/column.tsx

fix(column): Add missing `displayName`

---

renovate.json

chore(root): Add Renovate

---

packages/markdown/package.json
packages/markdown/src/markdown.spec.tsx
packages/markdown/src/markdown.tsx

- Updated bumped package  `md-to-react-email` to v3.0.3 which sanitises the parsed markdown output
- Updated the test cases
- Updated markdown component to use new syntax in `md-to-react-email`

chore(markdown): Bump md-to-react-email

---

packages/container/package.json

feat(container): Add exports for native ESM support

---

packages/column/package.json

feat(column): Add exports for native ESM support

---

packages/body/package.json

feat(body): Add exports for native ESM support

---

packages/button/package.json

feat(button): Add exports for native ESM support

---

packages/link/package.json

feat(link): Add exports for native ESM support

---

packages/html/package.json

feat(html): Add exports for native ESM support

---

packages/img/package.json

feat(img): Add exports for native ESM support

---

packages/hr/package.json

feat(hr): Add exports for native ESM support

---

packages/font/package.json

feat(font): Add exports for native ESM support

---

packages/head/package.json

feat(head): Add exports for native ESM support

---

packages/heading/package.json

feat(heading): Add exports for native ESM support

---

packages/text/package.json

feat(text): Add exports for native ESM support

---

packages/row/package.json

feat(row): Add exports for native ESM support

---

packages/section/package.json

feat(section): Add exports for native ESM support

---

packages/tailwind/package.json

feat(tailwind): Add exports for native ESM support

---

packages/render/package.json

feat(render): Add exports for native ESM support

---

packages/preview/package.json

feat(preview): Add exports for native ESM support

---

packages/markdown/package.json

feat(markdown): Add exports for native ESM support

---

packages/markdown/package.json
packages/markdown/src/markdown.spec.tsx

New release of `md-to-react-email` with some bug fixes, change logs can be found [here](https://github.com/codeskills-dev/md-to-react-email/releases/tag/v3.0.4)
- Updated the dependency to 3.0.4
- Updated the tests spec

chore(markdown): Update dependency

---

packages/body/package.json
yarn.lock

chore(body): Bump to v0.0.3

---

packages/button/package.json

chore(button): Bump to v0.0.10

---

docs/components/column.mdx

fix(columns): Docs example

---

demo/emails/apple-receipt.tsx
demo/emails/codepen-challengers.tsx
demo/emails/dropbox-reset-password.tsx
demo/emails/github-access-token.tsx
demo/emails/google-play-policy-update.tsx
demo/emails/netlify-welcome.tsx
demo/emails/nike-receipt.tsx
demo/emails/slack-confirm.tsx
demo/emails/stack-overflow-tips.tsx
demo/emails/twitch-reset-password.tsx
demo/emails/yelp-recent-login.tsx

This PR is part of the solution to #897 
- Reorganized email template layouts to adhere to HTML table standards and hierarchy.
- Ensured consistent use of `Section`, `Row` and `Column` components for email layout
- Apple-receipt
- Codepen-challenges
- Google-play-policy-update
- Netlify-welcome
- Nike-receipt
- Slack-confirm
- Stack-overflow-tips
- Twitch-reset-password
- Yelp-recent-login
- Nesting of `Row` in `Column` components should be discouraged. Instead nest a `Section` as it is valid to nest a `table` in a `td` and it follows the html spec of allowed content in a `td` [See spec here](https://html.spec.whatwg.org/multipage/tables.html#the-td-element)
- When using `Row` components, it is valid to keep content directly in the `Row` component or to nest in a `Column` as seen it the …

refactor(demo): Components usage

---

packages/row/readme.md
packages/section/readme.md

This PR is part of the solution to #897 
- Updated README examples for `row` and `column` usage

fix(packages): Update `readme` examples with `row` and `column`

---

docs/components/row.mdx
docs/components/section.mdx
docs/mint.json

This PR is part of the solution to #897 
- Adds `Row` to docs and explains its usage
- Updates `Section` docs to show usage example with `Row` and `Column`

feat(docs): Add `row` component

---

packages/markdown/package.json
packages/markdown/src/markdown.spec.tsx
packages/markdown/src/markdown.tsx

- Upgraded `md-to-react-email` from v3.0.4 to v4.0.0
- Added `showDataId` prop to control `data-id` attributes in the converted markdown to give finer control over final email output size
- Bump package version

chore(markdown): Update `md-to-react-email`

---

docs/cli.mdx
packages/react-email/source/index.ts

chore(docs): Add flag for skip-install flag

---

packages/react-email/source/utils/run-server.ts
yarn.lock

fix: Format

---

.github/workflows/tests.yml
package.json
turbo.json
yarn.lock

chore: Actions

---

docs/getting-started/migrating-to-react-email.mdx
docs/mint.json

chore(docs): Add migrating to react email page

---

packages/heading/package.json
packages/heading/src/heading.spec.tsx
packages/heading/src/heading.tsx
packages/heading/src/utils/spaces.ts
packages/heading/src/utils/utils.spec.ts

- Fix `withMargin` and `withSpace` utils
- Add tests for utils

fix(heading): Utils and add tests

---

packages/tailwind/package.json

chore: Upgrade Tailwind version

---

packages/react-email/package.json

Closes https://github.com/resendlabs/react-email/issues/918

chore(react-email): Bump to `v1.9.5`

---

README.md
docs/_snippets/localdev.mdx
package.json

chore: Update docs and readme to add `pnpm` command

---

demo/emails/codepen-challengers.tsx
demo/emails/dropbox-reset-password.tsx
demo/emails/github-access-token.tsx
demo/emails/koala-welcome.tsx
demo/emails/linear-login-code.tsx
demo/emails/netlify-welcome.tsx
demo/emails/stripe-welcome.tsx
demo/emails/vercel-invite-user.tsx
demo/emails/yelp-recent-login.tsx
docs/getting-started/manual-setup.mdx
packages/create-email/template/emails/stripe-welcome.tsx
packages/create-email/template/emails/vercel-invite-user.tsx

This PR updates the email templates in `demo/emails` to use the updated syntax for button padding

fix(demo): update email templates with correct <Button> syntax

---

packages/body/package.json
packages/button/package.json
packages/column/package.json
packages/container/package.json
packages/font/package.json
packages/head/package.json
packages/heading/package.json
packages/hr/package.json
packages/html/package.json
packages/img/package.json
packages/link/package.json
packages/markdown/package.json
packages/preview/package.json
packages/render/package.json
packages/row/package.json
packages/section/package.json
packages/tailwind/package.json
packages/text/package.json

chore(all): Bump version

---

packages/components/package.json
packages/tailwind/package.json
pnpm-lock.yaml

fixes https://github.com/resendlabs/react-email/issues/1002

fix: Upgrade `tw-to-css`

---

packages/components/package.json
pnpm-lock.yaml

fix(components): Upgrade Tailwind

---

docs/changelog.mdx
packages/render/package.json

chore(render): Bump to v0.0.9

---

docs/changelog.mdx
packages/components/package.json
pnpm-lock.yaml

chore(components): Upgrade `render`

---

demo/emails/koala-welcome.tsx
packages/body/src/body.spec.tsx
packages/column/src/column.spec.tsx
packages/container/src/container.spec.tsx
packages/font/src/font.spec.tsx
packages/hr/src/hr.spec.tsx
packages/html/src/html.spec.tsx
packages/img/src/img.spec.tsx
packages/link/src/link.spec.tsx
packages/render/src/render-async.ts
packages/row/src/row.spec.tsx
packages/section/src/section.spec.tsx

chore(all): Fix lint issues

---

packages/tailwind/package.json
pnpm-lock.yaml

chore(tailwind): Canary version

---

packages/components/package.json
packages/tailwind/package.json
pnpm-lock.yaml

chore(components): Bump Tailwind component

---

packages/react-email/package.json
pnpm-lock.yaml

chore(react-email): Bump `render@v0.0.10`

---

packages/create-email/src/index.js

fix(create-email): Tree function call

---

examples/resend/src/pages/api/send.ts

According to new resend email sending syntax, `sendEmail` method is no longer valid. Replaced it instead with the new method.

docs: update resend sending syntax

---

packages/code-block/package.json
packages/code-block/src/code-block.tsx

chore(code-block): Bump to v0.0.2

---

client/src/app/preview/[slug]/page.tsx
pnpm-lock.yaml

chore(client): Format

---

packages/render/package.json
pnpm-lock.yaml

chore(render): Bump to v0.0.12

---

packages/tailwind/src/utils/get-css-for-markup.ts

chore(tailwind): PostCSS type

---

pnpm-workspace.yaml

chore(root): Add `demo` to `pnpm` workspace

---

packages/inline-code/package.json

chore(inline-code): Remove `private`

---

apps/web/next.config.js

fix(web): Docs URL

---

package.json
pnpm-lock.yaml

chore(root): Upgrade `pnpm`

---

packages/components/package.json
packages/components/src/index.ts
pnpm-lock.yaml

feat(components): Add `CodeBlock`

---

apps/web/src/pages/examples/index.tsx

Improved indentation and spacing for better readability.
Grouped import statements.
Aligned object properties for better alignment and readability.
Removed redundant inline styles in the Image component.
Added comments for better understanding.
Retained the original structure and logic.

chore(web): Update index.tsx with clean code formatting

---

packages/components/package.json

chore(components): Bump to `v0.0.14`

---

packages/body/package.json
packages/tailwind/package.json
pnpm-lock.yaml

chore(body, tailwind): Upgrade `@babel/core`

---

packages/react-email/src/components/sidebar/sidebar-directory-children.tsx

https://github.com/resend/react-email/assets/1891339/3bef37c5-8320-4aaf-81e2-077d2b1fae69

feat(react-email): Add stagger animation file tree

---

apps/demo/emails/reviews/amazon-review.tsx
apps/demo/emails/welcome/netlify-welcome.tsx

fix(demo): `Column` missing `key`

---

packages/react-email/package.json

chore(react-email): Bump to `v2.0.0-canary.10`

---

packages/react-email/package.json
packages/react-email/src/actions/render-email-by-slug.tsx
packages/react-email/src/components/sidebar/sidebar-directory-children.tsx

fix(react-email): Revert URL slug

---

packages/react-email/package.json

chore(react-email): Bump to `v2.0.0`

---

apps/demo/package.json
pnpm-lock.yaml

chore(demo): Upgrade `react-email` to `v2.0.0`

---

packages/create-email/template/package.json

chore(create-email): Upgrade packages

---

packages/create-email/package.json

chore(create-email): Bump to `v0.0.22`

---

apps/web/src/components/example.tsx

fix(web): Examples images

---

apps/docs/changelog.mdx

feat(docs): Add changelog for Jan 19, 2024

---

packages/react-email/package.json
pnpm-lock.yaml

chore(react-email): Upgrade next to 14.1.0

---

apps/docs/components/tailwind.mdx

fix(docs): Tailwind example reference not being suffixed with .tsx

---

packages/react-email/src/cli/commands/build.ts
packages/react-email/src/cli/index.ts

Noticed a couple minor types when using the CLI

fix(cli): Minor typos in CLI

---

apps/docs/integrations/resend.mdx

I've made a small correction in the documentation where I found a minor typo.
This change improves the readability and accuracy of the documentation.
Thank you for considering this fix.

fix(docs): `resend.mdx` typo

---

packages/code-block/package.json
packages/components/package.json
pnpm-lock.yaml

- chore(code-block): Bump to 0.0.3-canary.0
- chore(components): Bump to 0.0.15-canary.0 and bump @react-email/code-block to 0.0.3-canary.0

chore(code-block, components): Bump for quick canary release

---

packages/code-block/package.json
packages/components/package.json
pnpm-lock.yaml

chore(components, code-block): Bump for canary release

---

apps/demo/emails/magic-links/aws-verify-email.tsx

Wrong image alt text for AWS template

---

apps/demo/package.json
packages/button/package.json
packages/code-block/package.json
packages/components/package.json
packages/create-email/package.json
packages/create-email/template/package.json
packages/react-email/package.json
pnpm-lock.yaml

- react-email  -> 2.1.0
- create-email -> 0.0.23
- components   -> 0.0.15
- button       -> 0.0.14
- code-block   -> 0.0.3

chore(button, code-block, components, create-email, react-email): Bump for stable release

---

packages/code-inline/package.json

chore(code-inline): Declare license into package.json

---

packages/components/package.json
packages/tailwind/package.json
pnpm-lock.yaml

- **chore(tailwind): Move to 0.0.15-canary.1 since 0.0.15-canary.0 already exists**
- **chore(components): Move dependency on @react-email/tailwind to 0.0.15-canary.1**
- **chore(deps): Update lockfile**

fix(tailwind, components): Already existing @react-email/tailwind version (0.0.15-canary.0)

---

apps/docs/roadmap.mdx

This PR updates the feature requests in roadmap.mdx from issues to discussions since the issues were moved to discussions.

fix(docs): update roadmap.mdx items from issues to discussions

---

packages/components/package.json
packages/create-email/package.json
packages/head/package.json
packages/tailwind/package.json
pnpm-lock.yaml

- **chore(tailwind): Bump to 0.0.16-canary.0**
- **chore(head): Bump to 0.0.8-canary.0**
- **chore(create-email): Bump to 0.0.25-canary.0**
- **chore(components): Bump dependency on @react-email/head to 0.0.8-canary.0**
- **chore(components): Bump dependency on @react-email/tailwind to 0.0.16-canary.0**
- **chore(components): Bump to 0.0.17-canary.0**
- **chore: Update lockfile**

chore(components, create-email, head, tailwind): Bump for canary release

---

apps/docs/components/tailwind.mdx

Fixes a couple small typos I found reading the component docs

fix(docs): minor tailwind doc typo fixes

---

apps/docs/introduction.mdx

Fixes the import for the `Support` snippet in the `/introduction` page.
This also fixes the isse #1515.
Before / After
https://github.com/resend/react-email/assets/90731442/56bafcfe-cc06-4716-8aaa-f36fee7e6ca9

fix(docs): update the import of the support snippet in the introduction page

---

apps/docs/changelog.mdx

- **add entry for 1st of July**
- **add entry for today**

chore(docs): Add entry for today and for the 1st of July

---

.changeset/beige-crews-battle.md
packages/create-email/.npmignore
packages/create-email/src/index.js

- **ignore node_modules and other things**
- **remove now uneeded filter and CHANGELOG removal**

fix(create-email): Error due to node_modules filter

---

apps/docs/components/code-inline.mdx

fix(docs): Missing component around `<CodeInline>`

---

apps/docs/changelog.mdx

chore(docs): Add changelog for July 23rd

---

apps/docs/changelog.mdx

chore(docs): Add changelog for August 22nd

---

apps/web/components/_components/layout.tsx
apps/web/components/article-with-image/inline-styles.tsx
apps/web/components/article-with-image/tailwind.tsx
apps/web/components/one-product/inline-styles.tsx
apps/web/components/one-product/tailwind.tsx
apps/web/src/components/component-preview.tsx
apps/web/src/components/component-view.tsx

fix(web): General component preview issues

---

apps/web/components/download-buttons/inline-styles.tsx
apps/web/components/download-buttons/tailwind.tsx
apps/web/components/single-button/inline-styles.tsx
apps/web/components/single-button/tailwind.tsx
apps/web/components/structure.ts
apps/web/components/two-buttons/inline-styles.tsx
apps/web/components/two-buttons/tailwind.tsx
apps/web/src/components/component-view.tsx

feat(web): Review Button content

---

apps/web/components/one-row-two-columns/inline-styles.tsx
apps/web/components/one-row-two-columns/tailwind.tsx

feat: Review Grid Content

---

apps/web/components/code-block-with-custom-theme/index.tsx
apps/web/components/code-block-with-line-numbers/index.tsx
apps/web/components/code-block-with-predefined-theme/index.tsx
apps/web/components/code-block-without-theme/index.tsx
apps/web/components/structure.ts

feat: Review Code Block content

---

apps/web/components/code-inline-with-different-colors/inline-styles.tsx
apps/web/components/code-inline-with-different-colors/tailwind.tsx
apps/web/components/simple-code-inline/inline-styles.tsx
apps/web/components/simple-code-inline/tailwind.tsx
apps/web/components/structure.ts

feat: Review Code Inline content

---

apps/web/components/header-and-four-paragraphs/inline-styles.tsx
apps/web/components/header-and-four-paragraphs/tailwind.tsx
apps/web/components/header-and-list-items/inline-styles.tsx
apps/web/components/header-and-list-items/tailwind.tsx
apps/web/components/header-and-numbered-list-items/inline-styles.tsx
apps/web/components/header-and-numbered-list-items/tailwind.tsx
apps/web/components/structure.ts

feat(web): Review Features content

---

apps/web/src/components/component-view.tsx

fix: Regression on code toolbar

---

apps/web/package.json
apps/web/src/app/layout.tsx
apps/web/src/components/menu.tsx
pnpm-lock.yaml

- 🧰 Fix responsive menu (topbar) with drawer for MB

🍔 fix: MB menu

---

apps/web/src/app/page.tsx

feat: Update CTA

---

apps/docs/changelog.mdx

feat(docs): Changelog for August 23rd

---

package.json
packages/eslint-config-custom/package.json
packages/react-email/package.json
pnpm-lock.yaml
turbo.json

- **update turbo**
- **update vite**
- **update pnpm**
- **update tsup**

chore(root): Upgrade internal dependencies

---

apps/web/next.config.js
apps/web/src/app/templates/page.tsx
apps/web/src/components/menu.tsx
apps/web/src/components/template.tsx

- **rename Examples to Templates**
- **add a redirect from /examples to /templates**
- **rename extra minor parts to Templates**

chore(web): Rename Examples to Templates

---

.changeset/young-terms-sparkle.md
packages/react-email/src/utils/static-node-modules-for-vm.ts

- **fix(react-email): MongoDB import failing compilation**

fix(react-email): MongoDB driver import breaking compilation

---

apps/web/src/components/component-view.tsx

feat(web): Make paths to assets into URLs for easy copy-pasting

---

.changeset/brave-llamas-reply.md
packages/react-email/package.json
pnpm-lock.yaml

This PR bumps chokidar to v4.0.1, thus removing 11 dependencies and improving TypeScript support. All packages build, and tests pass

Misc(react-email): bump chokidar to V4

---

apps/web/src/components/component-code-view.tsx

fix(web): Simple copy-paste components showing HTML instead of React

---

.changeset/kind-steaks-knock.md
packages/react-email/package.json
pnpm-lock.yaml

Bumps socket.io packages to fix vulnerability in `cookie`.

fix(react-email): bump socket.io and socket.io-client

---

.pnpmfile.cjs
pnpm-lock.yaml

chore(root): Ensure all components install a specific React 19 version

---

apps/docs/changelog.mdx

chore(docs): Add changelog for the 4th of November

---

apps/web/src/app/layout.tsx

This PR aims to fix side scrolling, especially on the components page.

fix(web): Side scrolling

---

apps/docs/changelog.mdx

chore(docs): Add changelog for November 8th

---

.changeset/wet-beans-run.md
packages/render/src/browser/render-async.tsx
packages/render/src/browser/render.tsx
packages/render/src/node/render-async.tsx
packages/render/src/node/render.tsx

fix(render): remove destructuring of react-dom/server import

---

apps/docs/getting-started/migrating-to-react-email.mdx

chore(docs): Remove automated section on MJML migration

---

.changeset/pink-berries-relate.md
packages/markdown/package.json
pnpm-lock.yaml

chore(markdown): Update md-to-react-email

---

.changeset/dull-poems-search.md
packages/markdown/package.json
pnpm-lock.yaml

fix(markdown): Memory leak due to outdated md-to-react-email

---

.changeset/strange-spiders-brush.md
packages/markdown/package.json
pnpm-lock.yaml

chore(markdown): Upgrade md-to-react-email

---

packages/react-email/src/cli/utils/preview/hot-reloading/create-dependency-graph.ts
packages/react-email/src/cli/utils/tree.ts
packages/tailwind/src/utils/react/map-react-tree.spec.tsx

This PR removes usage of `if/else`.

fix(all): Remove `if/else` usage

---

benchmarks/tailwind-component/src/benchmark-0.0.12-vs-local-version.ts
packages/react-email/src/cli/utils/preview/get-env-variables-for-preview-app.ts
packages/tailwind/integrations/_tests/utils/run-testing-command.ts

fix(all): Use node protocol

---

apps/demo/emails/receipts/apple-receipt.tsx
packages/tailwind/src/tailwind.spec.tsx

Preferred to self-closing elements.

fix(all): Self-closing elements

---

packages/button/src/button.tsx
packages/button/src/utils/parse-padding.ts
packages/heading/src/utils/spaces.ts
packages/react-email/src/cli/commands/dev.ts

Use number namescape instead of relying on global ones.

fix(all): Use number namespace

---

apps/web/src/app/not-found.tsx
packages/react-email/src/cli/commands/export.ts
packages/react-email/src/cli/utils/preview/serve-static-file.ts

This PR fixes the usage of unecessary template literals.

fix(all): Template literals

---

README.md

Added extra existing integration options to the readme file

fix(readme): add other integrations in readme

---

.changeset/pre.json
examples/aws-ses/CHANGELOG.md
examples/aws-ses/package.json
examples/mailersend/CHANGELOG.md
examples/mailersend/package.json
examples/nodemailer/CHANGELOG.md
examples/nodemailer/package.json
examples/plunk/CHANGELOG.md
examples/plunk/package.json
examples/postmark/CHANGELOG.md
examples/postmark/package.json
examples/resend/CHANGELOG.md
examples/resend/package.json
examples/scaleway/next/CHANGELOG.md
examples/scaleway/next/package.json
examples/scaleway/node/CHANGELOG.md
examples/scaleway/node/package.json
examples/sendgrid/CHANGELOG.md
examples/sendgrid/package.json
packages/components/CHANGELOG.md
packages/components/package.json
packages/create-email/CHANGELOG.md
packages/create-email/package.json
packages/create-email/template/CHANGELOG.md
packages/create-email/template/package.json
packages/render/CHANGELOG.md
packages/render/package.json
pnpm-lock.yaml

chore: Bump for canary release

---

.changeset/angry-bugs-sing.md
package.json
packages/react-email/package.json
packages/react-email/src/actions/email-validation/check-images.spec.ts
packages/react-email/src/actions/email-validation/check-images.spec.tsx
packages/react-email/src/actions/email-validation/check-images.ts
packages/react-email/src/actions/email-validation/check-links.spec.tsx
packages/react-email/src/actions/email-validation/check-links.ts
packages/react-email/src/components/button.tsx
packages/react-email/src/components/icons/icon-image.tsx
packages/react-email/src/components/sidebar/checking-results.tsx
packages/react-email/src/components/sidebar/image-checker.tsx
packages/react-email/src/components/sidebar/link-checker.tsx
packages/react-email/src/components/sidebar/sidebar.tsx
pnpm-lock.yaml

feat(react-email): Image validation checking

---

apps/docs/components/html.mdx

fix(docs): yarn install command in html.mdx

---

apps/docs/integrations/overview.mdx
apps/docs/integrations/scaleway.mdx
apps/docs/introduction.mdx
apps/docs/mint.json
apps/docs/package.json
apps/docs/snippets/integrations.mdx
pnpm-lock.yaml
pnpm-workspace.yaml

Added card components to redirect users to integrations

fix(docs): Missing links to some integrations

---

.github/workflows/tests.yml
apps/web/package.json
apps/web/src/app/api/check-spam/__snapshots__/check-spam.spec.tsx.snap
apps/web/src/app/api/check-spam/check-spam.spec.tsx
apps/web/src/app/api/check-spam/check-spam.ts
apps/web/src/app/api/check-spam/route.ts
apps/web/src/utils/spam-assassin/__snapshots__/parse-pointing-table-rows.spec.ts.snap
apps/web/src/utils/spam-assassin/parse-pointing-table-rows.spec.ts
apps/web/src/utils/spam-assassin/parse-pointing-table-rows.ts
apps/web/src/utils/spam-assassin/send-to-spamd.ts
apps/web/vitest.config.ts
packages/react-email/src/cli/commands/testing/export.spec.ts
pnpm-lock.yaml
turbo.json

feat(web): Check Spam API

---

apps/docs/changelog.mdx
apps/docs/components/code-block.mdx

fix(docs): fixed typo in docs

---

packages/react-email/src/actions/email-validation/check-compatibility.ts
packages/react-email/src/components/toolbar/linter.tsx
packages/react-email/src/utils/linting.ts

- **only include errors for compatibility issues**
- **don't show partially supported statusses on compat checking**
- **remove Hey from compatibility checking**

feat: Improve actionability of compatibility issues

---

packages/react-email/src/app/preview/[...slug]/page.tsx
packages/react-email/src/components/toolbar.tsx
packages/react-email/src/components/toolbar/code-preview-line-link.tsx
packages/react-email/src/components/toolbar/compatibility.tsx
packages/react-email/src/components/toolbar/linter.tsx
packages/react-email/src/utils/linting.ts
packages/react-email/src/utils/load-stream.ts

- **feat: Separate the compatibiliy checking into another tab for the toolbar**
- **remove logs**

feat: Separate the compatibiliy checking into another tab for the toolbar

---

packages/react-email/src/components/code.tsx
packages/react-email/src/components/toolbar/code-preview-line-link.tsx
packages/react-email/src/components/toolbar/linter.tsx

- **fix typo**
- **center the link by using scroll margin instead of just the effect**

fix: Weird scrolling on code preview when switching tabs

---

packages/react-email/src/components/code.tsx

feat: Make all line numbers clickable to share LoC

---

apps/demo/emails/reviews/airbnb-review.tsx

feat: address linter feedback for "reviews" emails

---

apps/demo/emails/reset-password/dropbox-reset-password.tsx
apps/demo/emails/reset-password/twitch-reset-password.tsx

feat: address linter feedback for "reset-password" emails

---

packages/react-email/src/components/toolbar.tsx

feat: empty state toolbar

---

.changeset/sour-deers-speak.md
packages/react-email/src/cli/utils/preview/serve-static-file.ts
packages/react-email/src/components/toolbar/use-cached-state.ts

- **fix stored value as undefined giving warnings**
- **fix errors if static files don't exist**
- **do not log any error if the static file doesn't exist**
- **aadd changeset**

fix: Linting hanging due to missing images

---

apps/demo/emails/receipts/apple-receipt.tsx
apps/demo/emails/receipts/nike-receipt.tsx

fix(demo): address linter feedback for "receipts" emails

---

packages/react-email/src/components/toolbar.tsx

feat: info should not open toolbar

---

packages/react-email/src/components/toolbar.tsx
packages/react-email/tailwind.config.ts

https://github.com/user-attachments/assets/87a81835-ad0a-4b55-b7fc-f693c1b97c6b

feat: new loading sate

---

packages/react-email/src/components/toolbar.tsx
packages/react-email/src/components/toolbar/results.tsx

https://resend.slack.com/archives/C058BM22A13/p1743097730394639

fix: align table

---

packages/react-email/src/components/toolbar/linter.tsx

feat: Improved consistency for http status

---

packages/react-email/src/app/layout.tsx
packages/react-email/src/app/page.tsx
packages/react-email/src/app/preview/[...slug]/preview.tsx
packages/react-email/src/components/code-container.tsx
packages/react-email/src/components/code.tsx
packages/react-email/src/components/resizable-wrapper.tsx
packages/react-email/src/components/shell.tsx
packages/react-email/src/components/sidebar/sidebar.tsx
packages/react-email/src/components/toolbar.tsx
packages/react-email/src/components/topbar.tsx

fix: Preview and code view clipping with toolbar open

---

.changeset/dry-tips-do.md
packages/react-email/src/cli/utils/preview/serve-static-file.ts

- **fix(react-email): Static files not being found properly**

fix(react-email): Static files regression

---

.changeset/itchy-coins-remain.md
packages/react-email/src/app/globals.css
packages/react-email/src/app/preview/[...slug]/preview.tsx
packages/react-email/src/components/shell.tsx
packages/react-email/src/components/toolbar.tsx

fix: Small design details

---

apps/docs/changelog.mdx

feat(web): add changelog for March 27th

---

.changeset/pretty-tables-repeat.md
packages/create-email/CHANGELOG.md
packages/create-email/package.json
packages/create-email/template/CHANGELOG.md
packages/create-email/template/package.json
packages/react-email/CHANGELOG.md
packages/react-email/package.json
pnpm-lock.yaml

chore: Bump for patch release

---

.changeset/grumpy-steaks-brake.md
packages/text/src/text.tsx
packages/text/src/utils/parse-margins.ts

fix(text): properly parse margin on the text component

---

apps/docs/changelog.mdx

- **add changelog for April 4th**
- **add changelog for April 1st**

feat(docs): Changelog entry for April 4th and April 1st

---

.changeset/fifty-streets-kick.md
packages/create-email/CHANGELOG.md
packages/create-email/package.json
packages/create-email/template/CHANGELOG.md
packages/create-email/template/package.json
packages/react-email/CHANGELOG.md
packages/react-email/package.json
pnpm-lock.yaml

chore(create-email, react-email): Bump for release

---

apps/docs/changelog.mdx

chore(docs): Add changelog for April 8th

---

packages/components/package.json
packages/react-email/package.json

- **add improved scripts**
- **install after build**

chore(root): Improve prepare scripts

---

examples/aws-ses/package.json
examples/mailersend/package.json
examples/nodemailer/package.json
examples/plunk/package.json
examples/postmark/package.json
examples/resend/package.json
examples/scaleway/next/package.json
examples/scaleway/node/package.json
examples/sendgrid/package.json
pnpm-lock.yaml
pnpm-workspace.yaml
turbo.json

chore(root): Deatch examples from workspace

---

examples/aws-ses/package.json
examples/mailersend/package.json
examples/nodemailer/package.json
examples/plunk/package.json
examples/postmark/package.json
examples/resend/package.json
examples/scaleway/next/package.json
examples/scaleway/node/package.json
examples/sendgrid/package.json

chore(examples): Remove versions, unpin dependencies

---

package.json
packages/tailwind/integrations/integrations.spec.ts
packages/tailwind/integrations/nextjs/package-lock.json
pnpm-lock.yaml
vitest.workspace.ts

chore(root): Upgrade vitest to 3.1.1

---

apps/web/components/bento-grid/inline-styles.tsx
apps/web/components/bento-grid/tailwind.tsx
apps/web/components/customer-reviews/inline-styles.tsx
apps/web/components/customer-reviews/tailwind.tsx
apps/web/components/list-with-image-on-left/inline-styles.tsx
apps/web/components/list-with-image-on-left/tailwind.tsx
apps/web/components/simple-list/inline-styles.tsx
apps/web/components/simple-list/tailwind.tsx
apps/web/components/simple-pricing-table/inline-styles.tsx
apps/web/components/simple-pricing-table/tailwind.tsx
apps/web/components/simple-rating-survey/inline-styles.tsx
apps/web/components/simple-rating-survey/tailwind.tsx
apps/web/components/two-tiers-with-emphasized-tier/inline-styles.tsx
apps/web/components/two-tiers-with-emphasized-tier/tailwind.tsx

- **fix discrepancies between bento-grid and two-tiers-with-emphasized-tier**
- **fix discrepancies in simple-pricing-table**
- **fix discrepancies in simple-list**
- **fix discrepancies in list-with-image-on-left**
- **fix discrepancies in simple-rating-survey**
- **fix discrepancies in customer-reviews**
- **lint**

fix(web): Discrepancies in copy-paste component variants

---

benchmarks/tailwind-component/src/emails/with-tailwind.tsx

fix(benchmarks): linter

---

.changeset/wet-guests-share.md
packages/tailwind/src/utils/css/resolve-all-css-variables.spec.ts
packages/tailwind/src/utils/css/resolve-all-css-variables.ts

- **add test that confirms the problem**
- **add proper support for multiple variables in the same declaration**

fix(tailwind): Declarations with multiple variables not being resolved

---

package.json
pnpm-lock.yaml

- **update turbo to 2.5.0**
- **upgrade pnpm to 10.8.1**

chore(root): Update pnpm and turborepo

---

.github/workflows/lint.yml
.github/workflows/tests.yml
.github/workflows/version.yml

- **pin version of pnpm action setup**
- **remove n**
- **pin version of buildjet cache action**
- **narrow down permissions for workflows**

fix(ci): Possible security issues

---

renovate.json

chore: Make renovate only rebase when conflcited

---

.changeset/tiny-bears-train.md
packages/react-email/src/cli/commands/export.ts

Console out the build error so we get more hints of why it's failing instead of just "Failed to build emails"

Console out build error

---

packages/react-email/package.json
packages/react-email/src/cli/utils/preview/hot-reloading/get-imported-modules.spec.ts
packages/react-email/src/cli/utils/preview/start-dev-server.ts
packages/react-email/tailwind.config.ts
packages/react-email/tsconfig.json
packages/react-email/tsup.config.ts

This also should fix the Vercel demo deploy

fix(react-email): Proper Node 18 support

---

.changeset/curly-cameras-ask.md
packages/text/src/text.spec.tsx
packages/text/src/text.tsx

fix(text): User's style not having priority

---

.github/workflows/release-canary.yml

chore: name release canary workflow according to Resend's standard

---

.changeset/open-pears-sink.md
packages/text/src/__snapshots__/text.spec.tsx.snap
packages/text/src/text.spec.tsx
packages/text/src/utils/compute-margins.spec.ts
packages/text/src/utils/compute-margins.ts

fix(text): Numerical margin values being overwritten with 0

---

.changeset/free-sides-grin.md
packages/render/src/browser/render.tsx
packages/render/src/node/render.tsx

Meant for #1953
All current tests are passing. this also progresses #2176

fix(render): reactDOMServer import on browser and some bundlers

---

.changeset/stupid-ghosts-decide.md
packages/react-email/src/utils/improve-error-with-sourcemap.ts
packages/react-email/src/utils/types/error-object.ts

fix(react-email): prettier errors causing NextJS serialization error

---

.changeset/spotty-items-teach.md
packages/react-email/src/app/layout.tsx
packages/react-email/src/components/sidebar/sidebar.tsx
packages/react-email/src/components/toolbar.tsx
packages/react-email/src/components/toolbar/spam-assassin.tsx

fix(react-email): Preview server's background gradient inteferring with the user's colors

---

apps/docs/contributing/codebase-overview.mdx
apps/docs/contributing/development-workflow/1-setup.mdx
apps/docs/contributing/development-workflow/6-editing-the-components.mdx

feat: chris suggestions
